### ISSUE TITLE
how to install a project locally?

### ISSUE THREAD

**Issue by kiberlain** [retypeapp/retype#11]
I can not deploy to vercel hosting

**Comment by fabriciomurta** [comment]
In case you are serving the files elsewhere not the website root, you need to [set retype.json's `base` config](https://retype.com/configuration/project/#base).

So if the local server path is something like `wwwroot/docs`, so public address would be http://myhost.com/docs), the retype.json file would need to have `"base": "docs"`  to honor that path.

In other words, it should point to your documentation's root relative to the website's.
