### ISSUE TITLE
Broken relative links

### ISSUE THREAD

**Issue by AdamBrianBright** [retypeapp/retype#112]
I'm not very familiar with front-end stuff, but from what I see, relative links (to "parent directory") are broken. Maybe dynamic link substitution will solve this?

Example found on your very docs:
`../components` should _in theory_ lead to `retype.com/components`, but leads to `retype.com/guides/components`

_(There's a resolved link shown at left bottom corner)_

![image](https://user-images.githubusercontent.com/15821800/128145474-f9e58dcc-ccc5-4e73-8c16-4d580e52efd0.png)

P.S. If such behaviour as relative links shouldn't exist, at least fix this particular link please :D

**Comment by geoffreymcgill** [comment]
Thanks for pointing out the broken link. In `v1.8.0`, the link resolution process was refined, but it would appear this scenario where a relative link to a folder (`../components/`) requires additional attention. We might have made the wrong decision on how that type of link should be resolved.

We are discussing right now and coming up with a plan. If a patch release is required, we can implement the fix and make a new release quickly.

I will keep this thread up to date.

Thanks again for letting us know about this issue.

**Comment by geoffreymcgill** [comment]
We are in the process of improving the logic Retype uses to resolve links. Once complete, the original scenario will be resolved correctly. 

The plan is to include this bug fix (or is it an enhancement? 🤷) in a `v1.8.1` patch release. With some luck, the patch will be released tomorrow. If not, it will be very soon thereafter. As soon as we have this fix in place and well tested, we will be releasing `v1.8.1`.

**Comment by geoffreymcgill** [comment]
This issue has been fixed and the fix was included in `v1.8.1`, which has now been released.

Hope this helps.
