### ISSUE TITLE
Odd author formatting

### ISSUE THREAD

**Issue by fotrimzi** [retypeapp/retype#114]
Can I let the screenshot speak for itself? (Just updated from 1.7.0 to 1.8.0)

<img width="172" alt="Screenshot 2021-08-04 at 22 15 52" src="https://user-images.githubusercontent.com/85963311/128241465-d55b820c-0a96-404e-be62-165e1b6436ee.png">

Meta data:

```
---
author: A. U. Thor
---
```

**Comment by geoffreymcgill** [comment]
argh. :man-facepalming: I not exactly sure what is going on here. I think Retype is parsing `A. U. Thor` as chunk of markdown and is outputting the value as an ordered list.

We will fix. somehow.

Thanks for the report.

**Comment by geoffreymcgill** [comment]
We found the issue and will be fixing right away. We are making a `v1.8.1` patch release (see #112) and will be including this fix in that patch. The patch will be released very soon, hopefully tomorrow.

As a possible temporary work around for you, removing the space between `A.` and  `U.` will render correctly. The work around value would be:
```yml
---
author: A.U. Thor
---
```
Once `v1.8.1` is released, the work around would not be required and your original value will render correctly.

I will keep this thread updated with our progress.

Hope this helps.

**Comment by fotrimzi** [comment]
Good work finding it. Good luck fixing it. Meanwhile I'll simply change my pen name.

**Comment by geoffreymcgill** [comment]
This issue has been fixed and the fix was included in v1.8.1, which has now been released.

Hope this helps.

Thanks again for reporting this error.

**Comment by fotrimzi** [comment]
Thanks and yw but now I have this too https://github.com/retypeapp/retype/issues/116.

**Comment by fabriciomurta** [comment]
We just fixed that too by releasing 1.8.2 at once. Should be good for you now.

**Comment by fotrimzi** [comment]
Yes 1.8.2 fixes this too, thanks.
