### ISSUE TITLE
retype.com missing destination page sections for V1.8 Roadmap links

### ISSUE THREAD

**Issue by ApolonTorq** [retypeapp/retype#115]
The [V1.8 Roadmap links](https://retype.com/roadmap/#v180-) don't all resolve to page anchors that exist.
e.g.
https://retype.com/configuration/project/#url
https://retype.com/configuration/page/#author
https://retype.com/configuration/page/#category
https://retype.com/configuration/page/#date
https://retype.com/configuration/page/#redirect
https://retype.com/configuration/page/#visibility

**Comment by geoffreymcgill** [comment]
Should be better now.
