### ISSUE TITLE
Retype 1.8.1 broken

### ISSUE THREAD

**Issue by DannyBen** [retypeapp/retype#116]
After upgrading from 1.8.0 (which worked) to 1.8.1, I am getting this error when running retype:

```
$ retype
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/vagrant/.config/yarn/global/node_modules/retypeapp/platforms/linux-x64/retype EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /home/vagrant/.config/yarn/global/node_modules/retypeapp/platforms/linux-x64/retype',
  path: '/home/vagrant/.config/yarn/global/node_modules/retypeapp/platforms/linux-x64/retype',
  spawnargs: []
}
```

- It was installed with yarn.
- Uninstalling and reinstalling did not help.
- Downgrading back to 1.8.0 goes back to a working version

**Comment by geoffreymcgill** [comment]
Thanks for the report. I'm not sure what happened here. I'm on it.

**Comment by fabriciomurta** [comment]
A workaround for that is just
`chmod ug+x /home/vagrant/.config/yarn/global/node_modules/retypeapp/platforms/linux-x64/retype`

But that'd be an extra step necessary once per installation. This should no longer be necessary in any further release, but we will add means to avoid this from repeating in the future.

**Comment by DannyBen** [comment]
But.... are you releasing 1.8.2 or re-releasing a fixed 1.8.1?

**Comment by geoffreymcgill** [comment]
We are releasing `v1.8.2` right away.

**Comment by DannyBen** [comment]
> We are releasing v1.8.2 right away.

cool. so no workaround needed for end users.

**Comment by geoffreymcgill** [comment]
Once `v1.8.2` is published, I will write up a quick summary of what happened. As with many catastrophic failures, it wasn't just one process that failed.

The `v1.8.2` packaging is running right now. It takes ~30 minutes for all the tests and packaging to complete.

**Comment by fotrimzi** [comment]
Thank you, 1.8.2 working (for me).

**Comment by fabriciomurta** [comment]
Only NPM packages for OS X and Linux were affected by this problem. 1.8.2 eliminated the issue with these versions.

The win32 and win64 NPM packages and dotnet tool weren't affected by this issue.

**Comment by DannyBen** [comment]
I can also confirm, 1.8.2 works. I am closing this ticket, assuming nobody else needs it open.
