### ISSUE TITLE
Site reloads while navigating through pages in v1.8

### ISSUE THREAD

**Issue by axonasif** [retypeapp/retype#117]
Hello, recently after upgrading to `v1.8` I am noticing that my site is having to reload the whole page when going over another page. I did not notice this behavior previously. Although https://retype.com/ seems to not have this issue.

My site link: https://wiki.supreme-gamers.com/

To confirm that this isn't a server-side issue I also upgraded my retypecli and ran it locally but the issue still persisted.
It's not a big issue but it'd be nice if I could know what's going wrong here.

Could not find anything useful on console-logs either, something is probably going wrong with ajax.

Thanks!

**Comment by geoffreymcgill** [comment]
Hi. I cloned your repo and ran your project locally using the latest Retype release. The pages are being loaded super fast as a single-page web application.

When I view your live [website](https://wiki.supreme-gamers.com/), it appears two additional `.js` files are being added to the page, not by Retype. The two are:

- https://wiki.supreme-gamers.com/cdn-cgi/challenge-platform/h/g/scripts/invisible.js
- https://wiki.supreme-gamers.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js

Try turning off [Rocket loader](https://www.cloudflare.com/website-optimization/) that is being injected by CloudFlare and see if that solves the issue. I suspect this is the what's causing the load problem.

I'm not sure what `invisible.js` is doing, but you can also try removing that file from the page.

Hope this helps.

**Comment by axonasif** [comment]
> Try turning off Rocket loader that is being injected by CloudFlare and see if that solves the issue. I suspect this is the what's causing the load problem.
It seems to be the issue. Although it wasn't in the previous retype version. Thanks for pointing it out.

I already had a cloudflare page-rule for the site since cloudflare intensive-caching was causing some other troubles.
Now also disabled Rocket-loader for this site specifically.
![image](https://user-images.githubusercontent.com/39482679/128658829-32a5da58-16f0-4be1-b6b7-62efd8fd6787.png)

So I think now you could add a note in the retype docs for those using cloudflare :+1:

**Comment by M1O0O** [comment]
I got the same error so I tried to see if Rocket Loader was activated but it isn't, so I put my CloudFlare in developer mode and the problem "disappeared".
I put in quotes because the page does not refresh, so I have to do it manually, hence my changes are taken.

**Comment by geoffreymcgill** [comment]
As of the upcoming v3.1.0 release, Retype now supports Cloudflare Rocket Loader. There are no changes required in your project, other than building with Retype v3.1.0 once it is released. 

Even though Retype is now working well, we would still recommend disabling Cloudflare Rocket Loader within your Cloudflare admin panel.
