### ISSUE TITLE
Opening anchor links in tabs doesn't display the correct anchor point

### ISSUE THREAD

**Issue by ApolonTorq** [retypeapp/retype#118]
To reproduce:
- Go to https://retype.com/roadmap/#v180-
- Left mouse clicking on each of the # links in the V1.8.0 section results in a correct navigation.
- Right mouse clicking or control clicking to open those same # links in a Chrome browser tabs does not result in a correct navigation.

**Comment by fabriciomurta** [comment]
Oh, I see, the anchor links and any side bars' links are overriding chrome default ctrl+click to open in new tab/window. Sorry for taking so long to respond, this really looks inconsistent.

**Comment by geoffreymcgill** [comment]
This issue has been fixed in the `v1.11.0` release, which is now [available](https://github.com/retypeapp/retype/releases/tag/v1.11.0).
