### ISSUE TITLE
How can i create nested folder/subfolder ?

### ISSUE THREAD

**Issue by haiclover** [retypeapp/retype#120]
i tried this way but it doesn't work
![image](https://user-images.githubusercontent.com/20736458/129079810-6aceb154-9e3e-4c00-91be-50cf22a9333e.png)

**Comment by geoffreymcgill** [comment]
Hi @haiclover. You are not providing enough information to diagnose the issue.

**Comment by haiclover** [comment]
i want to create folder inside folder

**Comment by geoffreymcgill** [comment]
> i want to create folder inside folder

Okay, that should not be a problem.

Closing this issue. If you can provide relevant details on the exact issue you are experiencing, and/or any error messages, or really just absolutely anything that might help us diagnose the problem, then we can reopen and take another look.

**Comment by haiclover** [comment]
![image](https://user-images.githubusercontent.com/20736458/129081617-c69ea97a-37fe-4051-876a-4cbf66c38fef.png)
![image](https://user-images.githubusercontent.com/20736458/129081635-19ae00d4-820e-435a-8109-cd9e34d403ba.png)
@geoffreymcgill

**Comment by haiclover** [comment]
@geoffreymcgill 
Can you help me ???

**Comment by fabriciomurta** [comment]
Can you host your test doc project in a temp github repo so we can take a look?
