### ISSUE TITLE
Deploy: add Docker

### ISSUE THREAD

**Issue by DanielRamp** [retypeapp/retype#122]
What is the reason for not having a predefined `Dockerfile`, `docker-compose.yml` or a prebuilt docker image on e.g. [docker hub](https://hub.docker.com/)?

**Comment by fabriciomurta** [comment]
1. shouldn't be too hard to come up with one, custom as the person needs
2. nobody ever asked; we chose a minimum distribution set and if something else gets requested, we'd at least be spending time in something that's going to be used. :)

**Comment by geoffreymcgill** [comment]
Thanks for the request. It's something we have been discussing recently. The only reason for not having it... we just haven't got to it yet. We have some other tasks finishing up soon and will prioritize this functionality to be next.

**Comment by DannyBen** [comment]
Having a docker image with retype is the easy part:

### `Dockerfile`

```dockerfile
FROM node
RUN npm install retypeapp --global
WORKDIR /app
VOLUME /app
ENTRYPOINT ["retype"]
```

### `docker-compose.yml`

```yaml
services:
  retype:
    build: .
    image: retypeapp/retype
    volumes:
      - .:/app
    ports:
      - 3000:5000
    command: watch   # or omit
```

### Build and run

```bash
# Build
$ docker build -t retypeapp/retype .
# or
$ docker-compose build

# Create an easy to use alias
$ alias retype='docker run --rm -it -v "$PWD:/app" retypeapp/retype'

# Or run manually
$ docker run --rm -it -v "$PWD:/app" retypeapp/retype

# Or with compose
$ docker-compose up retype
```

Perhaps the bigger challenge would be to have a *small* one based on alpine (the above image is 1.27 GB).

When I tried the above with `FROM node:alpine`, it does not seem to work.

Alpine brings the size down to 472MB, but when running it, you get the below error.

<details>
  <summary>Show Error</summary>
  
```
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype',
  path: '/usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype',
  spawnargs: []
}
```
</details>

**Comment by fabriciomurta** [comment]
It is as if the node_modules directory is not being preserved in the image, but the retype Node JS wrapper is.

Can you check if spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype exists in the generated image?

You'd probably need to define a [Docker Volume](https://docs.docker.com/storage/volumes/) with the path where node keeps the globally-installed modules, `/usr/local/lib/node_modules`. Maybe other paths, as needed.

**Comment by DannyBen** [comment]
Personally, I do not need a docker image for retype, I just thought I would post here for the benefit of @DanielRamp, and as a baseline for anybody in retype who might want to implement it.

> You'd probably need to define a Docker Volume

Unless I misunderstand your intentions, I don't think this is a solution. A retype image needs to include everything to run, and having a single volume to `$PWD` so users can make their config and markdowns accessible to the image.

> Can you check if spawn /usr/local/lib/node_modules/retypeapp/platforms/linux-x64/retype exists in the generated image?

When building with alpine, retype exists in the specified folder:

```bash
$ ls /usr/local/lib/node_modules/retypeapp/platforms/linux-x64
LICENSE  retype
```

**Comment by fabriciomurta** [comment]
This ENOENT issue makes no sense, the file is there but unable to execute. So maybe the running kernel in the docker image is not compatible with 64-bit linux binaries the `dotnet` tool creates.

**Comment by fabriciomurta** [comment]
What shows in your docker instance's `uname -a`?

**Comment by DannyBen** [comment]
> What shows in your docker instance's `uname -a`?

Doesn't it always show the version of the host?

```
# uname -a
Linux bec89c8f924b 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 Linux
```

Also - I hope that the official retype image can be smaller. 
Even the alpine one ends up at almost 500mb, which is large for a single tool.

**Comment by fabriciomurta** [comment]
By the digest name in [the DockerHub's taglist](https://hub.docker.com/_/node?tab=tags&page=1&ordering=last_updated&name=alpine), `node:alpine` should be pulling alpine 3.13, which [should be compatible with .NET 5](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine).

There's also different targetted platforms in which we would only support [the linux/amd64 one](https://hub.docker.com/layers/node/library/node/alpine3.13/images/sha256-65ccf08f9e0e15861e1d241ff90aeb293d86e080b68b5053b888ee38db887289?context=explore).

Well, after all, it shouldn't be that straightforward simple docker unless the right image, compatible with Retype, is chosen. We would need to run some tests and trials to tell what exact recipe that is.... In that sense, it would really be interesting to have a properly cooked up Retype Docker package, I guess. :)

**Comment by DannyBen** [comment]
> Well, after all, it shouldn't be that straightforward simple docker unless the right image, compatible with Retype, is chosen.

It is always an option to simply use `FROM ubuntu`, or even as I demonstrated, `FROM node`.

But being "docker friendly" means being able to run on alpine if possible in my book.

**Comment by fabriciomurta** [comment]
> Also - I hope that the official retype image can be smaller.
> Even the alpine one ends up at almost 500mb, which is large for a single tool.

There are two paths to follow towards that:
1. try a .NET aware alpine image (containing the `dotnet` tool). Then the Retype image size will be down to 8Mb. But then, we need to assess the overhead of having `dotnet` tool installed.
2. We are about to release target-specific NPM packages, so we can just target the image to the linux64 package to quarter the size of the retype overhead (and this should imply less overhead than installing the whole `dotnet` toolchain)

**Comment by DannyBen** [comment]
>try a .NET aware alpine image

I was looking at some of the [official dotnet images](https://hub.docker.com/_/microsoft-dotnet), but wasn't sure what is needed. Perhaps it would be just a matter of finding the right one and then `RUN dotnet tool retype` or whatever the command, and hopefully that's it.

**Comment by fabriciomurta** [comment]
If you want to give (2) a try, `npm install --global retypeapp-linux-x64@1.9.0-preview` in your Dockerfile. You are more than welcome to open a discussion with feedback of the forthcoming release. (we're still cooking proper changelogs, so bear with us until we can present something cool each release).

**Comment by fabriciomurta** [comment]
> > try a .NET aware alpine image
> 
> I was looking at some of the [official dotnet images](https://hub.docker.com/_/microsoft-dotnet), but wasn't sure what is needed. Perhaps it would be just a matter of finding the right one and then `RUN dotnet tool retype` or whatever the command, and hopefully that's it.

ya, that'd be `dotnet tool install --global retypeapp`; once that's done, retype would be added to path just like it is with NPM's, so it should be the only and only different step in the image building lifecycle.

**Comment by DannyBen** [comment]
Already had a sneak peak at your [fork's changelog](https://github.com/fabriciomurta/retype/releases/tag/v1.9.0) :)

**Comment by fabriciomurta** [comment]
That's information on an unofficial fork. We cannot guarantee clarity or accuracy in that fork's information. So, use that at your own risk and discretion.

**Comment by Blackvz** [comment]
The NPM/Yarn way does not seem to work on M1 Macs.

I am running a node container with: `docker run --platform=linux/amd64 -v $(PWD):/app -w /app -it node bash`

![image](https://user-images.githubusercontent.com/12122294/155411303-02a966fc-0e7e-4fc8-89e5-e18fe1f3336a.png)

**Comment by geoffreymcgill** [comment]
> The NPM/Yarn way does not seem to work on M1 Macs.
>
> I am running a node container with: `docker run --platform=linux/amd64 -v $(PWD):/app -w /app -it node bash`
>
> ![unnamed (2)](https://user-images.githubusercontent.com/62210/155417768-6ae2c970-99d4-4ad1-ada4-ef42ab01610d.png)

Hi @Blackvz,

It would appear the `Function not implemented` error is an issue with the Docker virtualization engine. We are investigating.

There appears to be a fix, but only when the host is on Windows. M1 Mac is obviously still causing a problem.

## See also

- https://github.com/Azure/azure-functions-core-tools/issues/2901
- https://github.com/docker/for-win/issues/5955

**Comment by Blackvz** [comment]
> > The NPM/Yarn way does not seem to work on M1 Macs.
> > I am running a node container with: `docker run --platform=linux/amd64 -v $(PWD):/app -w /app -it node bash`
> > ![unnamed (2)](https://user-images.githubusercontent.com/62210/155417768-6ae2c970-99d4-4ad1-ada4-ef42ab01610d.png)
> 
> Hi @Blackvz,
> 
> It would appear the `Function not implemented` error is an issue with the Docker virtualization engine. We are investigating.
> 
> There appears to be a fix, but only when the host is on Windows. M1 Mac is obviously still causing a problem.
> 
> ## See also
> * [Mac M1 Function Not Implemented Error docker/for-mac#5328](https://github.com/docker/for-mac/issues/5328)
> * ["Function not implemented" error on Mac M1, works on Ubuntu  Azure/azure-functions-core-tools#2901](https://github.com/Azure/azure-functions-core-tools/issues/2901)
> * ["Function not implemented" when trying to access a file within a container. Works fine from Windows. Need to restart Docker to fix. docker/for-win#5955](https://github.com/docker/for-win/issues/5955)

Deleted my post to try some more things out. Still no luck :(

But yes seems to be an Mac M1/ARM Docker Issue.

**Comment by fabriciomurta** [comment]
Hi! On your docker image, run native, it should work. Instead of `--platform=linux/amd64`, use one of the **ARM** alternatives. Then base your docker image off an equivalent [ARM image from Microsoft ASP.NET Core Runtime](https://hub.docker.com/_/microsoft-dotnet-aspnet), there are several arm64 variants you can choose from that would not require using QEMU (which causes the issue) so you could run Retype from your mac without issues. Then when you're ready to deploy and don't want to stack emulation (and your host is linux/amd64) you can just switch the platform.

I don't think docker team is worried about fixing this issue, so my guess is this is your best bet for the time being.

**Comment by fabriciomurta** [comment]
We have just tested the first release that included DockerHub images publishing integrated to the process. Now we should be keeping these images up to date. We're bound to write some guides on using it but your feedback is really appreciated, especially with practical use cases we could use as examples.

It basically supports images for Debian, Ubuntu and Alpine Linux distributions on 64-bit Intel/AMD, arm32 (Android, Raspberries?) and newer arm64 (Apple Silicon, Mac M1) architectures. Here's some docker commands to get a contained prompt with Retype available. It should choose architecture depending on your docker's guest, automatically.

```
# Latest Retype version on default (Debian) image
docker run --tty --interactive retypeapp/retype:latest
```

```
# Latest Retype version on Alpine image
docker run --tty --interactive retypeapp/retype:latest-alpine
```

```
# Stick to v2.2.0, Ubuntu image
docker run --tty --interactive retypeapp/retype:2.2.0-ubuntu
```

```
# Stick to v2.2.x, force Debian image (should the default ever change)
# This 2.2 tag means if 2.2.1 or 2.2.2 is released, they'll become this tag.
docker run --tty --interactive retypeapp/retype:2.2-debian
```

The repository with the whole collection of available image tags can be listed in https://dockerhub.com/r/retypeapp/retype

Using the specific arm64 images should allow containers to work in most cases while avoiding [the `Function not implemented` issue above](https://github.com/retypeapp/retype/issues/122#issuecomment-1049315554).

**Comment by DannyBen** [comment]
Just link correction: https://hub.docker.com/r/retypeapp/retype

**Comment by geoffreymcgill** [comment]
@DannyBen Thanks for pointing out the broken link. 🍻  I fixed the link.

**Comment by mariusrak** [comment]
Hi, is there any way to upgrade retype from inside the docker container?
