### ISSUE TITLE
Allow blank target on button component

### ISSUE THREAD

**Issue by geoffreymcgill** [retypeapp/retype#132]
### Discussed in https://github.com/retypeapp/retype/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **etienne-bechara** August 25, 2021</sup>
Currently, the only way I found to create a link that opens in a new tab, is to write pure HTML inside the markdown:

```
<a href="https://www.google.com" target="_blank">Google</a>
```

It would be nice if the button component supported that feature:

```
[!button target="blank" text="Google"](https://www.google.com)
```</div>

**Comment by fabriciomurta** [comment]
The option was added to 1.9.0 and should be working now.
- [Documentation on button's target parameter](https://retype.com/components/button/#target).
