### ISSUE TITLE
Incorrect highlighting of inner table of content links

### ISSUE THREAD

**Issue by DannyBen** [retypeapp/retype#134]
When clicking on the inner navigation (righthand side), the highlighting of the selected link gets a life of its own and seems to "predict the future".

![screencast](https://user-images.githubusercontent.com/2405099/131155139-24d66b08-5862-44db-8d3e-ed2ca3c7102c.gif)

You can hopefully reproduce it on [my bashly retype site](https://bashly.dannyb.co/configuration/command/) - note that I have increased font size on my Windows, so the de-facto resolution behaves more tablet-like than desktop-like.

**Comment by geoffreymcgill** [comment]
The TOC scroll position bug has been fixed. Performance was also improved by ~5x too. It's all working much better now. 

The enhancements will be available within the upcoming `Retype v2.0` release. Just upgrading to `v2.0` will be all that is required. No changes to your `.md` page or any configuration are required.

Hope this helps.

**Comment by geoffreymcgill** [comment]
This issue has been fixed and is now available as of Retype [`v2.0.0-preview`](https://github.com/retypeapp/retype/discussions/287#discussioncomment-2321442). The final `v2.0.0` release should be early next week. Any feedback you have is greatly appreciated.

**Comment by DannyBen** [comment]
It works beautifully now. And I like the fact that it highlights multiple headlines when multiple headlines content is visible.
