### ISSUE TITLE
Questions and suggestions: will multi-site and multi-version support be available?

### ISSUE THREAD

**Issue by DemoMacro** [retypeapp/retype#142]
The retype app experience basically meets my needs, but will there be support for multiple version switching and multiple sites (or multiple repositories)?

**Comment by fabriciomurta** [comment]
You want something like a dropdown to choose a software's version to show documentation of? Like, [Microsoft .NET](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks?view=net-5.0) and [NodeJS docs](https://nodejs.org/dist/latest-v14.x/docs/api/), perhaps?

And, I can't see an example with multi site/repo spanning documentation.

For documentation involving multiple sites, you can always nest repositories ([git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)) or simply place them together and craft retype.ini to pull docs off the common, top level directory. So, perhaps an alternative to the "multiple sites" would be just to allow more than one [project config's input](https://retype.com/configuration/project/#input) so it merges all paths in subdirectories, maybe?

This really sounds interesting, and I'd see the different versions a bit trickier as they could be split just by directories, but they may also require git interaction (checkout tag + make docs + checkout next tag...). But it would sure be much easier than maintaining the dropdown and manual (or scripted) assemble the docs with valid links between versions.

**Comment by DemoMacro** [comment]
Yes, you got my point. The usability of retype would be much higher if there was an option to select the version or language of a document. For example, by storing documents in different directories and switching between them when selecting a certain version. Multiple languages or multiple versions would be desirable features.
