### ISSUE TITLE
Feature Request: Widescreen mode

### ISSUE THREAD

**Issue by R-Studio** [retypeapp/retype#172]
Hi almost everything in this project is perfect, but in a world where screens are getting wider and wider it would be very nice to have a "widescreen mode".

### Before any changes
![image](https://user-images.githubusercontent.com/7498854/137149937-3984c999-8603-41a8-8194-f83a07610093.png)

### After editing the css temporarly
![image](https://user-images.githubusercontent.com/7498854/137150060-0a7059cc-c108-4db4-98e6-b34444ecb50c.png)

I achieved this by temporary editing the **retype.css** `.container` and removed the css property **max-width** (Chrome development tools):
![image](https://user-images.githubusercontent.com/7498854/137148122-60cfd9c2-981a-4ad8-859a-604a6fd2a63b.png)

**- Do you have any idea to achieved this permanently?**
**- In a future release: Can you add a option for this (for example define the **max-width** in the `retype.yml`)?**

_Thanks for this amazing project, this is exactly what I was looking for!_

**Comment by geoffreymcgill** [comment]
Hi. Thanks for the kind words and feedback. 

The existing content `max-width` was chosen very deliberately to optimize the readability for your website visitors. Allowing the content to flow full width on a wider screens creates sub-optimal readability, so I'm not a fan of making this change or enabling as a config option.

**Comment by geoffreymcgill** [comment]
We are working on some options to scale the page width and add some additional configuration. Targeting the Retype `v1.12` release. I don't have any details yet as we are still in planning and early prototyping, but progress is being made. I will try to keep this thread updated with our progress.

**Comment by R-Studio** [comment]
This sounds very nice! I will wait for v1.12 👍🏽 -> Again thanks for this great project!!

**Comment by adhadse** [comment]
This might look good on a 32'' inch screen with 16:9 aspect ratio, but for ultrawide displays, like 34'' Dell U3419W with 21:9 aspect ratio and super-ultrawide displays like 49' inch Dell U4919DW, with a massive wide aspect ratio of 32:9 ; a user will have to move his/her head from complete left to right.

This will be very inconvenient. What are your thoughts @geoffreymcgill @R-Studio?

**Comment by R-Studio** [comment]
@adhadse I understand your considerations and **it makes sense to not remove the css property `max-width`**, but 1400px is the default and this is for me to small (Because I want to display more content with less scrolling). 
That's why It would be great if we can define the `max-width` property inside the project settings to a custom value for example to 2000px or whatever.
_If I had the skills to add this "feature" I will working on this, but unfortunately I don't have it._

**Comment by R-Studio** [comment]
@geoffreymcgill I saw the release v2.x and it is so beautiful, nice! 👍🏽 
But when I had read the release notes right, the max-width is still not configurable?

**Comment by geoffreymcgill** [comment]
@R-Studio There is not a config but you can override the `max-width` with your own custom value. See,
https://github.com/retypeapp/retype/discussions/294#discussioncomment-2361480

Hope this helps.
