### ISSUE TITLE
Default page goes to a blank screen [✅SOLVED]

### ISSUE THREAD

**Issue by ghost** [retypeapp/retype#175]
Hello, when a new device (without cached files of my site) goes to my docs ([https://docs.contactit.fr](https://docs.contactit.fr)), it goes to a blank page. 

![in](https://user-images.githubusercontent.com/61574808/137452688-b278381b-4900-4ee9-ba36-be428499dfa9.gif)

I have to refresh the page to display all the content.

![ftPf8gP5ov](https://user-images.githubusercontent.com/61574808/137453237-2fa897a0-7953-47c2-92ca-e84d199682bf.gif)

It is not happen in localhost. It is on my vps..

I thought about the cache with the .htaccess but after re-initializing it, no.

**Comment by febreze21** [comment]
It was the modpagespeed's rewrite-image function who breaks something with retype.
