### ISSUE TITLE
Is there a setup that allows me to open the built index.html locally without a server?

### ISSUE THREAD

**Issue by joonaspaakko** [retypeapp/retype#193]
There is the `url` config, but the asset paths always seem to start with at the very least `/` making it so I have to spin up a server to view the documentation and I'd like an option where I didn't have to do that.

**Comment by fabriciomurta** [comment]
Point `url` to `mydomain.com/mysubdir`.

Either way you can always [`retype run`](https://retype.com/guides/cli/#retype-run) or [`retype watch`](https://retype.com/guides/cli/#retype-watch).

The latter is very smart and you can see your rendered page, make edits and, as you save the source file, the page gets updated with latest changes, so you should give it a try.
