### ISSUE TITLE
Search does not work for Japanese Titles

### ISSUE THREAD

**Issue by RickCogley** [retypeapp/retype#197]
Cool project. I'd love to use it and would pay for "pro" if I could fully use Japanese in it. 

I see that search works only on page titles at this time (not full text), and that `search.json` under the output folder is where the search index is being created. However, the search function does not work if the searched title is Japanese language, even if I search the full title exactly. 

Usually, the problem with open source systems and Japanese language search, is that Japanese (indeed CJK languages) doesn't usually use spaces. The search tokenizer has to be set to operate differently from English or other languages that have spaces, but, normally I'd expect an exact match of something that is indeed in the index, to result in a search hit. 

( _Regarding settings in another system, for instance, I used [fuse](https://fusejs.io/) search on a site and had to set its options like so:_

https://github.com/eSolia/eSolia_2018/blob/main/layouts/_default/search.html#L106

_...to get it to work with Japanese._ )

Regarding retype (at least the local `retype watch` served site), oddly enough, the "Filter" box in the sidebar _does indeed_ work to filter Japanese, both the full string of the titles and substrings therein. 

### What I tried

* create a markdown file, and put `# 我が輩は猫である` at the top, so this becomes the title that should be searched
* confirm existence in search index after doing `retype build`. 
* search 我が輩は猫である or 我が輩 or 猫である in the search box, getting no hits
* search the same in "Filter" and get hits on the names (always works even for files in sub folders and sub-sub folders)

### What I expected

To be able to successfully search the full match of a title at least given apparent default settings, and hopefully substrings.

**Comment by geoffreymcgill** [comment]
Hi @RickCogley. Thanks for the excellent defect report. 👍 We will investigate right away and figure out what is required to get the search working properly with Japanese language content.

**Comment by RickCogley** [comment]
Thank you, appreciate that

**Comment by geoffreymcgill** [comment]
We have completed some initial research and it looks like we should be able to get automatic language detection and language specific search indexing working within Retype. Also with manual `language` project level config override. 

Ideally, in a future release, you will not have to make changes to your content or Retype app configuration. The Japanese language search will just magically start working correctly.

Thanks again for reporting this issue. 😄

**Comment by geoffreymcgill** [comment]
@RickCogley Looks like we have multi-language search working.

<img width="494" alt="Screen Shot 2021-11-10 at 4 15 03 AM" src="https://user-images.githubusercontent.com/62210/141043297-e6c75561-97f1-4fb1-987a-44e8965f89c6.png">

The core functionality is working, although we still have a lot of testing and other refinements to complete. We are targeting the `v1.12` release.

**Comment by RickCogley** [comment]
Oh that's cool! Let me know when you need testing.

**Comment by geoffreymcgill** [comment]
Multi-language search support has been added to Retype `v1.11` and will be included in the upcoming release. Detection of Japanese language strings is automatically handled by Retype, so there is nothing you will need to do on your side to enable the new functionality. Just upgrade to the next release and rebuild your project.

Many languages are handled automatically. Here is a table documenting all the supported languages and whether they are automatically detected by Retype:

| Language   | Identifier | Auto-detection |
| ---------- | ---------- | -------------- |
| Arabic     | `ar`       | 🔴 |
| Chinese    | `zh`       | 🟢 |
| Danish     | `da`       | 🟢 |
| Dutch      | `nl`       | 🟢 |
| English    | `en`       | 🟢 |
| Finnish    | `fi`       | 🔴 |
| French     | `fr`       | 🟢 |
| German     | `de`       | 🟢 |
| Hindi      | `hi`       | 🔴 |
| Hungarian  | `hu`       | 🔴 |
| Italian    | `it`       | 🟢 |
| Japanese   | `ja`       | 🟢 |
| Norwegian  | `no`       | 🟢 |
| Portuguese | `pt`       | 🟢 |
| Romanian   | `ro`       | 🔴 |
| Russian    | `ru`       | 🟢 |
| Spanish    | `es`       | 🟢 |
| Swedish    | `sv`       | 🟢 |
| Tamil      | `ta`       | 🔴 |
| Thai       | `th`       | 🔴 |
| Turkish    | `tr`       | 🔴 |
| Vietnamese | `vi`       | 🔴 |

If your project includes content from one of the languages NOT automatically detected, you will need to manually add the `search.languages` config to your project `retype.yml` file. The following sample demonstrates adding search support for Turkish and Russian languages:

```
search
  languages:
    - tr
    - ru
```

Another `.yml` format for arrays is also supported. Both work the same. 

```yml
search
  languages: [tr, ru]
```

@RickCogley Thanks again for making us aware of this issue originally.

Hope this helps.

**Comment by RickCogley** [comment]
Awesome!

--
Rick Cogley
090-9959-5452

**Comment by RickCogley** [comment]
@geoffreymcgill hi, just curious, when do you expect to release `v1.11`?

**Comment by geoffreymcgill** [comment]
Right away. Just need to close issue #201, and we just verified it should be working. Once closed, we will be releasing `v1.11`.

**Comment by RickCogley** [comment]
Cool, I’ll test it.

--
Rick Cogley
M: +81-90-9959-5452

**Comment by geoffreymcgill** [comment]
Multi-language search is now supported in Retype [`v1.11.0`](https://github.com/retypeapp/retype/releases/tag/v1.11.0). Hope this helps.

**Comment by RickCogley** [comment]
Appreciate it, I'm testing it now and it indeed does work!

**Comment by RickCogley** [comment]
Oops, sorry, I spoke too soon. It appeared to work, but when I test text inside the pages, it doesn't. The search index does not have anything but titles, still. 

```
❯ retype --version
1.11.0
```

Is there a setting I need to make to make it use full text?

**Comment by RickCogley** [comment]
What _is_ working, is substrings within the titles, which did not work before. So 1.11 is still not "full text" I take it?

**Comment by geoffreymcgill** [comment]
Full text search is currently not supported. The following thread provides a good discussion on the topic:

https://github.com/retypeapp/retype/issues/59

Headings are indexed. For a full text search, an external service is going to be required.

**Comment by RickCogley** [comment]
Got it. I think if we can't do full text (the index would be large, I'm sure), if it could index descriptions if that is set in the front matter, that itself would be really helpful, in lieu of full text.

**Comment by RickCogley** [comment]
And per #59 it does include headings.

**Comment by geoffreymcgill** [comment]
Indexing descriptions is an excellent idea and should not be a problem. We want to experiment with some other options as well. We just need to fit that work into the schedule.

**Comment by RickCogley** [comment]
yes, indeed. Thank you for this; it's super easy to set up
