### ISSUE TITLE
NPM Installation on M1 Macbook

### ISSUE THREAD

**Issue by harrysolovay** [retypeapp/retype#201]
I'm on a 14 inch 2021 macbook pro (chip is the Apple M1 Max), and the installation keeps getting stuck here:

<img width="913" alt="Screen Shot 2021-11-13 at 2 50 54 PM" src="https://user-images.githubusercontent.com/4893548/141657227-3602c860-9b2a-4482-a64d-7412521d1675.png">

Any advice on getting the CLI working would be greatly appreciated. Thank you!

**Comment by geoffreymcgill** [comment]
Hi @harrysolovay. We don't have a M1 Mac (yet) to test the installer on but we will do some research to try and figure out what might be going wrong. 

What version of NPM are using? Check using the `npm -v` command.

If you are not the latest version of NPM on that machine, can you try upgrading to the latest and retest the `npm install retypeapp --global` install.

**Comment by harrysolovay** [comment]
I'm on version `8.1.3` (the latest version). The global installation fails as well :/

Please let me know if there's any other info I can provide to help with diagnosis. Thank you!

**Comment by fabriciomurta** [comment]
Have you tried switching to the x64 architecture version of Node? I found this blog post that may prove interesting. It looks like what's hanging is NPM, so we're not even getting to the point where Retype runs.

https://www.jurnalanas.com/node-js-mac-m1/

This is from June this year, so it may be outdated.

**Comment by harrysolovay** [comment]
I have, yes. Very strange. Suddenly I miss Intel chips.

**Comment by fabriciomurta** [comment]
You're on NodeJS 15.x right? I read version 14 is known not to work on M1s for some reason.

**Comment by geoffreymcgill** [comment]
Hi @harrysolovay. We are working on this issue and hope to have a plan in place within 24 hours. Looks like we might have to make an M1 targeted build. Or, at least sign the build with XCode.

We were anticipating releasing Retype `v1.11` right away, but I feel figuring out this M1 issue is a high priority issue and I'd like to see the fix included in `v1.11`. Hopefully we will know more very soon.

**Comment by harrysolovay** [comment]
No rush. Thank you!

**Comment by geoffreymcgill** [comment]
Hi @harrysolovay 

In a new **Terminal** instance, try [installing](https://retype.com/guides/getting-started/#install) Retype again using the command `npm install retypeapp --global`.

We tested installing on a fresh M1 Mac and Retype installed perfectly using NPM.

Our M1 Mac is running NPM `v6.14.13` and Node `v14.17.3`.

<img width="475" alt="Screen Shot 2021-11-18 at 9 57 12 AM" src="https://user-images.githubusercontent.com/62210/142387121-67c0af36-829f-4d78-846a-9c27985f55c2.png">

Retype installation should work without an issue on M1 Mac OS.

If the installation is still failing, please post a copy of any Terminal messages you receive. Let us know either way.

**Comment by geoffreymcgill** [comment]
Hopefully there is not a difference between M1 and M1 Max. We were only able to test on an M1 box.

**Comment by fabriciomurta** [comment]
I have just set up npm 8.1.3 + node 16.13.0 using `nvm` in the mac m1 above and it worked just fine, No hang during npm process, and I built this very repository using it. It is, of course, running under Rosetta 2 (see "Intel" in the "kind" column in picture below)

![image](https://user-images.githubusercontent.com/10730372/142445478-dafa0878-7f5e-4971-8feb-9733ab7efca4.png)

macOS did its work for itself, I didn't instruct it to do anything particular.

**Comment by geoffreymcgill** [comment]
Closing this issue for now. 

If anyone discovers that they cannot install Retype on a Mac M1|M1 Pro|M1 Max machine, please let us know what error messages you are receiving. We will re-open this issue and investigate right away. 

For now, installation doesn't seem to be a problem, just ensure you are using one of the install commands listed in the [Getting Started](https://retype.com/guides/getting-started/#install) guide. 

We are also looking into creating a stand-alone app, so using a package manager would not be required. NPM, Yarn, and dotnet would still be fully supported. Those options are not going anywhere. We would just add another app installer option.
