### ISSUE TITLE
Not render numbering with dot properly 

### ISSUE THREAD

**Issue by Dominic-Preap** [retypeapp/retype#207]
Hello, thank you for your awesome tool. I'm writing my simple project using arch42 template but seem like I have one problem. 

## Bug Report

I try to put manual numbering with `dot` in header in `*.md` page but it cannot properly render as show below.
- `2. Title`
- `2.1. Subtitle`

**Code Input**
![image](https://user-images.githubusercontent.com/14802170/142234677-581454ef-532f-4a11-bc17-9f4a45800c42.png)

**Result**
![image](https://user-images.githubusercontent.com/14802170/142234582-d52a6f45-ab94-43f5-b001-7b520cff35da.png)

## Expected behavior
It should render numbering with dot properly or is there any automatic numbering

## Environment

<pre><code>
  App version: 1.10.0

  For Tooling issues:
  - Node version: v14.17.4
  - Platform:  Windows 

  Others:
  
</code></pre>

**Comment by geoffreymcgill** [comment]
Hi @Dominic-Preap. Thanks for the report. We will investigate this right away and try to figure out what's going wrong. Getting this fixed should not be a problem.

**Comment by ColonelPanicks** [comment]
I've just hit this issue with folder configuration too. 

Steps to replicate:
```shell
retype init folder-label-test
cd folder-label-test
mkdir -p mydir/another-dir
echo 'label: My Directory' > mydir/index.yml
echo '# Some Page' > mydir/another-dir/apage.md
echo "label: '1. Another Directory'" > mydir/another-dir/index.yml
retype watch
```

Some things I've tried with the `index.yml` are: 
- Single quoting the label string (`label: '1. Another Directory'`) -> Folder label: `Another Directory`
- Double quoting the label string (`label: "1. Another Directory"`) -> Folder label: `Another Directory`
- Entering any character (other than a space) before the number (`label: '.1. Another Directory'`) -> Folder label: `.1. Another Directory`
- Removing the period from the number (`label: '1 Another Directory'`) -> Folder label: `1 Another Directory`

So this definitely seems related specifically to a number + period being handled differently somewhere.

**Comment by ColonelPanicks** [comment]
I've found a way to make this work in the meantime... Backslach-escaping the period causes the title to render as expected.

```
label: '1\. Another Directory'
```
<img width="300" alt="Screenshot 2022-02-09 at 11 13 07" src="https://user-images.githubusercontent.com/27725639/153187245-81385cf7-3f75-4893-a31b-752eae403c60.png">

**Comment by AndreyChechel** [comment]
The root cause of the issue - Retype tries to render the configured label as a numbered list, whereas we wouldn't expect that.

Another possible workaround would be to replace a space ` `  symbol with `&nbsp;`

```yml
label: 1.&nbsp;Another Directory
```
