### ISSUE TITLE
Corrupted website configuration on firefox

### ISSUE THREAD

**Issue by WilsontheWolf** [retypeapp/retype#225]
On firefox web browser, retype apps show a [FATAL]: Corrupted website configuration error. Nothing in the logs or requests looks off. I can replicate this on https://enmap.evie.dev and even the offical https://retype.com website.

https://user-images.githubusercontent.com/33164598/143490975-cc88d489-19cb-4549-90cc-276710860e85.mp4

**Comment by WilsontheWolf** [comment]
An update it seems to be dark reader. Disabling it doesn't cause issues.

**Comment by geoffreymcgill** [comment]
Very interesting. 

Can you try disabling all, or at least some of your Firefox browser extensions.

Can you also try clearing the browser cache?

I tested both enmap.evie.dev and retype.com in my Firefox instance (macos), and do not get that error.

We are running some more tests and will try to reproduce locally.

**Comment by WilsontheWolf** [comment]
It seems that dark reader seems to be causing issues. I actually seems to get this on chromium browsers with the extension too. Seems to be something recent because I've used the extension for a long time and its not have issues before. Thanks for the fast responce.

**Comment by geoffreymcgill** [comment]
Can you isolate the browser extension? Which extension is triggering the issue?

**Comment by geoffreymcgill** [comment]
ah, is it "dark reader"? I will investigate.

**Comment by WilsontheWolf** [comment]
Yes thats correct, its the extension dark reader.

**Comment by geoffreymcgill** [comment]
Confirmed. I reproduce the error. Investigating...

**Comment by geoffreymcgill** [comment]
Hi @WilsontheWolf. We have this scenario fixed and will be releasing Retype `v1.11.1` today with the fix included.

Thanks again for reporting the issue.

**Comment by geoffreymcgill** [comment]
This issue has been fixed and included in the Retype [`v1.11.1`](https://github.com/retypeapp/retype/releases/tag/v1.11.1) release.

Hope this helps.
