### ISSUE TITLE
Flash of error before page load

### ISSUE THREAD

**Issue by AndreyChechel** [retypeapp/retype#226]
### Discussed in https://github.com/retypeapp/retype/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **RickCogley** November 21, 2021</sup>
Using github pages to deploy, when I load my retype site (https://help.esolia.pro) pages before they get cached by the browser (seems like the cache expired overnight), I see this error flash for a split second, in the upper left of the browser screen, before the page content loads:

```
FATAL: corrupted website configuration
```

The site is working and I get no fatal errors locally with `retype watch --verbose`, but the error is disconcerting, so I wanted to ask if anyone knows about this... </div>

**Comment by geoffreymcgill** [comment]
This issue has been fixed and included in the Retype [`v1.11.1`](https://github.com/retypeapp/retype/releases/tag/v1.11.1) release.

Hope this helps.
