### ISSUE TITLE
Ability For Search With Third Party Integrations

### ISSUE THREAD

**Issue by apidev234** [retypeapp/retype#237]
Hello,

This would be glad if you enable integration for Search Engines Like [Algolia](https://algolia.com/docsearch) or [Typesense](https://typesense.org) / [MeiliSearch](https://meilisearch.com)

---
Or, You Guys And Some Either Devs Who Support This Idea either me and others can make a web crawler and build a search engine ourselves for retype.

Would be a great idea!

**Comment by fabriciomurta** [comment]
We already have plans to implement our own full-site search service, so at first, 3rd-party searches won't be our focus. This can, of course, change in the future, so keep an eye out at our issues and releases. Soon, news could be coming out about that.

It's a bit comprehensive, but take your time and read thru #224 and you'll see what the plans are -- and that discussion is the best place you can add your thoughts to upcoming advanced features.

**Comment by Grafikart** [comment]
In the meantime is there a way to customize the template so we could inject custom script (for instance to use [docsearch](https://docsearch.algolia.com)

**Comment by geoffreymcgill** [comment]
Hi @Grafikart. The Retype search component is getting a nice upgrade with the next major release. 

DocSearch is interesting, but every single one of their _checklist_ items are requirements or limitations that you will not have to deal with if using Retype:

> 1. You must be the owner of the website, or at least have the permissions to update its content. You'll need to include a JavaScript snippet to your frontend to implement DocSearch.

If you are building a Retype website, I guess it could be assumed that you are the owner, but you will not have to include any JavaScript snippets in your frontend to implement Retype search. With Retype, your search will just work and continue to improve with each new Retype release.

> 2. Your website must be publicly available. We do not host search indices for websites that are only available after authentication or are hosted on a private network.

This sucks. With Retype, your website can be private. Your Retype search will function exactly the same on a private or public website. 

> 3. Your website must be a technical documentation of an open source project or a technical blog. We do not index commercial content.

Retype websites can be anything you want. A travel blog, commercial website, technical docs, crypto whitepaper, API docs, etc. Whatever you want. Your Retype search will work the same no matter what content you are publishing.

> 4. Your website must be production ready. We won't index empty websites nor those filled with placeholder content. Please, wait until you have written some documentation before applying. We would be happy to help you as soon as you have a steady design.

Production ready or not, your Retype search will be updated instantly with each new build and you will not have to wait for a third-party search service to crawl your website.

---

I understand that the current Retype search component is weak. We are making good progress and if you stick with Retype, your search will only get better with each new release.

Hope this helps

**Comment by geoffreymcgill** [comment]
The search functionality has been significantly improved as of the Retype [`v2.0.0-preview`](https://github.com/retypeapp/retype/discussions/287#discussioncomment-2321442) release, including the new full-text search index option. 

The [retype.com](https://retype.com/) website is using the new search.

At least for the foreseeable future, Retype will not be adding 3rd party search component integration.
