### ISSUE TITLE
Alert component's content should be of full width

### ISSUE THREAD

**Issue by sarsamurmu** [retypeapp/retype#242]
This is how it looks
![chrome_5KdjxMHnI8](https://user-images.githubusercontent.com/44255990/146681721-331409d3-076c-46a3-b043-6d6adb89b074.png)
As you can see this caused by this `div.pr-5.ml-3` element
![chrome_OO8N6jdmoA](https://user-images.githubusercontent.com/44255990/146681809-f4aa5c1e-db74-4291-9fd7-a97d2b9bfb4c.png)
Gets fixed just by adding `w-full` class to the element
![chrome_kLphNal9Hm](https://user-images.githubusercontent.com/44255990/146681880-5e9d1319-5d58-4754-9c33-e0e49372a4ab.png)

**Comment by geoffreymcgill** [comment]
This issue has been fixed and will be included in the upcoming Retype `v2.0` release.

Thanks for reporting the defect. 

Hope this helps.
