### ISSUE TITLE
Error executing retype watch 

### ISSUE THREAD

**Issue by fomundifr** [retypeapp/retype#250]
Good afternoon, I am running retype watch and I get the following error: 

```
/usr/local/lib/node_modules/retypeapp/platforms/osx-x64/retype: 5: Syntax error: ")" unexpected
```

**Comment by fabriciomurta** [comment]
Do you have any other information like Node JS version?

**Comment by fomundifr** [comment]
I have nodejs version 16.13.1

**Comment by fabriciomurta** [comment]
I have just tested with Node 16.13.2 and it works on mac. The file it points "syntax error" is a binary/executable file, it seems for some reason you host is interpreting it as a script. Can you share more system specs and the exact steps you followed to install retype on your end?

The command `md5 /usr/local/lib/node_modules/retypeapp/platforms/osx-x64/retype` should return:
```
MD5 (/usr/local/lib/node_modules/retypeapp/platforms/osx-x64/retype) = 4d0d67afb0e43e324fabb9c633dacbf6
```

For Retype version 1.11.2. Did it work in the past and stopped working at some point?

**Comment by fomundifr** [comment]
![Screenshot_20220113-065716_Termux](https://user-images.githubusercontent.com/81490579/149273991-c18fabe3-a0ad-4dfd-b471-142c7e532c49.jpg)

**Comment by fomundifr** [comment]
In the terminal termux I am using:  proot-distro login ubuntu

**Comment by fomundifr** [comment]
I still haven't been able to use Retypeapp, and I still get that error

**Comment by fabriciomurta** [comment]
What system, OS and architecture/processor you're trying to run retype from?

- If that's a Mac, Linux or Windows, you can just install Node from nodejs.org and run in its native shell.
- If elsewhere, you may be able to run NuGet version of retype via `dotnet` tool

What doesn't add up to me is that your system informs it is a mac x64, but it is not clear why do you use termux on a mac PC; besides your screenshot suggests you are running it from a phone. Retype is supported where .NET application is supported, that is: Linux, Windows and Mac OS.

Custom builds of .NET should allow Retype to run in other systems via its NuGet package. This means installing the `dotnet` tool on your command prompt and Retype is not tested in other systems, so we cannot tell what may be missing as some systems' support may not be fully implemented. Retype is based on .NET 5.x, installing .NET 6 may be okay, but we're keeping our Retype tests on .NET 5 until we migrate to .NET 6.

**Comment by fabriciomurta** [comment]
Looking a bit about `proot-distro`, it seems it uses QEMU to enable running software for other architecture on arm-based hosts and maybe others.

And it looks like it has trouble handling .NET applications, thus it seems it is still not supported by .NET, the underlying technology behind Retype according to dotnet/runtime#13648.

**Comment by AmreshSinha** [comment]
I am facing this issue too!
I have a arm64 architecture host on oracle cloud and I am running a arm version of debian bullseye docker image. Inside that image I am running my repo which uses retype as a documentation generator. But it throws this same error
```
Syntax error: ")" unexpected
```
Any help will be appreciated!
Thanks!

**Comment by fabriciomurta** [comment]
Retype NPM package is not compatible with the arm64 architecture. It works on linux/debian as long as it is in an x64-64 arch. This is a limitation from our upstream requirement -- .NET 5.

If you can get .NET 5 or 6 installed on your Debian arm64 image (install the `dotnet` commandline available), then you should be able to run Retype with its NuGet package -- install with `dotnet tool install --global retypeapp`

Otherwise, switching to an AMD/Intel x86-64 architecture should allow you to install and run the NPM package.

**Comment by AmreshSinha** [comment]
Thanks! I have made it work now on arm.
Here is the Dockerfile:
```
FROM ubuntu:18.04

RUN apt-get update -y
RUN apt-get install nodejs npm curl wget -y
RUN npm install -g n && n 16 && npm i --g npm@latest

# Installing Dotnet 5 arm64 and setting new PATH for dotnet cli to work
RUN mkdir /lib/dotnet-arm64 && tar zxf /tmp/dotnet-sdk-5.0.100-linux-arm64.tar.gz -C /lib/dotnet-arm64
ENV DOTNET_ROOT=/lib/dotnet-arm64
ENV PATH=/lib/dotnet-arm64:$PATH
ENV PATH=$PATH:/root/.dotnet/tools
RUN dotnet tool install --global retypeapp

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./package.json /usr/src/app/
RUN npm install && npm cache clean --force
COPY ./ /usr/src/app
ENV NODE_ENV production
ENV PORT 80
EXPOSE 80

RUN retype build
CMD node app.js
```

**Comment by fabriciomurta** [comment]
Way to go! That's a pity that .NET 5 didn't make stock builds for such distros, it becomes hard to maintain if the upstream does not support the platform. Glad we have the NuGet package to aid.
