### ISSUE TITLE
Uncaught SyntaxError: 60

### ISSUE THREAD

**Issue by ammarahm-ed** [retypeapp/retype#256]
Getting this error on production build. Usually happens when navigating from Side Menu or even at launch sometimes in all browsers.
```
Uncaught SyntaxError: 60
    Fe retype.js:20523
    io retype.js:23325
    ho retype.js:23337
    zn retype.js:21733
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    qn retype.js:21683
    qr retype.js:23088
    <anonymous> retype.js:23508
    4359 retype.js:23521
    cn retype.js:6385
    sn retype.js:6356
    a retype.js:6348
    on retype.js:6350
    M retype.js:5198
    I retype.js:5194
    y retype.js:5059
    J retype.js:5629
    mount retype.js:4841
    mount retype.js:20460
    <anonymous> retype.js:24085
    <anonymous> retype.js:24086
    g retype.js:195
    notifyApplicationAfterPageLoad retype.js:2250
    pageBecameInteractive retype.js:2169
    pageIsInteractive retype.js:1773
    pageIsComplete retype.js:1776
    interpretReadyState retype.js:1759
retype.js:20523
    Fe retype.js:20523
    io retype.js:23325
    ho retype.js:23337
    zn retype.js:21733
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    zn retype.js:21758
    zn retype.js:21760
    qn retype.js:21683
    qr retype.js:23088
    <anonymous> retype.js:23508
    4359 retype.js:23521
    cn retype.js:6385
    sn retype.js:6356
    a retype.js:6348
    on retype.js:6350
    M retype.js:5198
    I retype.js:5194
    y retype.js:5059
    J retype.js:5629
    mount retype.js:4841
    mount retype.js:20460
    <anonymous> retype.js:24085
    <anonymous> retype.js:24086
    g retype.js:195
    notifyApplicationAfterPageLoad retype.js:2250
    pageBecameInteractive retype.js:2169
    pageIsInteractive retype.js:1773
    pageIsComplete retype.js:1776
    interpretReadyState retype.js:1759
```

**Comment by AndreyChechel** [comment]
Hi @ammarahm-ed 

Thanks for reporting this defect. Retype uses Vue.JS in the browser to render generated pages and sometimes it fails to render page content treating it as a template. We're aware of several occurrences of that error and already working on the fix It'll be available in the next release.

If you were able to isolate what exact syntax causes the error you posted, that would help us to verify that scenario and ensure it's fixed too. Any details are appreciated.

**Comment by ammarahm-ed** [comment]
@AndreyChechel It just crashes on almost any page randomly. I have been unable to find what is causing the error.

The docs are available here: https://github.com/streetwriters/notesnook/tree/main/docs
And hosted here: https://docs.notesnook.com

It doesn't crash on local device. Even if I build it in production or run it in dev mode. It just crashes when deployed.

I hope that helps.

**Comment by AndreyChechel** [comment]
@ammarahm-ed thanks for providing the links. 

I was able to reproduce it constantly for the following page.
https://docs.notesnook.com/organizing-notes/how-do-i-organize-notes-using-colors/

We'll investigate and keep this thread updated.

**Comment by AndreyChechel** [comment]
The issue is caused by the additional scripts injected to generated pages, most likely by the script defining/processing `pagespeed.CriticalImages.checkImageForCriticality`.

It may correlate with the issue we aware of and fixing at the moment. So there is a chance that the reported issue will be fixed too, however, with no guarantee, since the injected scripts manipulate with the page markup and history and that obviously may collide with Retype logic.

**Comment by ammarahm-ed** [comment]
Hey @AndreyChechel Thanks for investigating. We were able to fix our issue with website crashing constantly. It was related to image paths that were relative and not pointing to the correct url in release build. Causing a crash. You can check the github repo to see what we changes we had to made to get it working again. 

I will close the issue now. Thanks!

**Comment by AndreyChechel** [comment]
Thanks for the update. We'll review your fix.
