### ISSUE TITLE
Retype does not work on linux arm64

### ISSUE THREAD

**Issue by SpicyTakis** [retypeapp/retype#273]
Trying to install retype on a linux arm64 machine, when i run retype it classifies it as osx-64x. Is there no support for arm64 devices?

**Comment by SpicyTakis** [comment]
![image](https://user-images.githubusercontent.com/67237931/153693120-6b0f6110-acc9-4c5c-84d4-757c8fd010d9.png)

**Comment by fabriciomurta** [comment]
The NPM packages doesn't. Use the NuGet package if you want to run it in linux-arm64. You need .NET 5 installed for it to work. Once .NET is installed, you install Retype with `dotnet tool install --global retypeapp`

**Comment by fabriciomurta** [comment]
See also #249 and #250.

**Comment by fabriciomurta** [comment]
Now with Retype version 2, the .NET version required has shifted to 6. It should work on ARM64 devices as well. We still don't support ARM platform from the NPM packages so .NET Runtime (ASP.NET Runtime actually) is required.
