### ISSUE TITLE
API Generation of C# Namespaces converts the CamelCase names to all lowercase except the first letter

### ISSUE THREAD

**Issue by ApolonTorq** [retypeapp/retype#277]
The issue occurs in V1.11.2 and earlier. For example, the namespace `OpenSmtp` is incorrectly displayed with page title of `Opensmtp`.

![image](https://user-images.githubusercontent.com/6407433/154831011-40626fc6-658c-44e5-b2b3-fe6ead5d418e.png)

**Comment by fabriciomurta** [comment]
This is also reproduced in MojeeIO namespace at [mojee docs](https://docs.mojee.io/)

![image](https://user-images.githubusercontent.com/10730372/155419122-a32e68c4-cf7e-4b5c-9ca3-c315fbd57c04.png)

It seems only the topmost namespace folder is affected by this. (in the picture above, only `MojeeIO` gets cased as `Mojeeio`)

**Comment by geoffreymcgill** [comment]
This issue has been fixed and will be included in the upcoming Retype `v2.0` release. No release date yet, but we're getting close. 

@ApolonTorq Thanks again for reporting the issue!

Hope this helps.
