### ISSUE TITLE
Sidebars are too wide on new project

### ISSUE THREAD

**Issue by itsthejoker** [retypeapp/retype#288]
Hi there! Hopefully this is just a config option that I'm missing somewhere. I've just deployed a brand new Retype project and so far it's AMAZING... but it doesn't look the same as your docs. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/5179553/157605830-7641f058-bb38-4f11-a83a-05f06a4e036f.png)

vs, in the same browser:

![image](https://user-images.githubusercontent.com/5179553/157605899-25d445cf-3ab9-4ac9-8145-c5a8ad3ead59.png)

How do I get the center content column to expand with the screen size so that the sidebars go back down to where they're supposed to be?

Deployment url: https://alexandriails.github.io/Alexandria/

Repo: https://github.com/AlexandriaILS/Alexandria

I appreciate any light you can shed on this. Thank you!

**Comment by fabriciomurta** [comment]
Hi, retype.com website is using our to-be-released `v2.0.0-preview` release. And among [its massive amount of changes](https://github.com/retypeapp/retype/releases/tag/v2.0.0-preview), it adjusts the document maximum width. Notice it is not necessarily fitting your window, it is just now with a wider "width tolerance" now.

Check our dedicated 2.0.0-preview discussion for more details in #287.

**Comment by geoffreymcgill** [comment]
Change the following two lines to use our new Retype [`v2.0.0-preview`](https://github.com/retypeapp/retype/discussions/287#discussioncomment-2321442) release:

https://github.com/AlexandriaILS/Alexandria/blob/master/.github/workflows/retype.yml#L17-L19

### Before

```yml
      - uses: retypeapp/action-build@v1

      - uses: retypeapp/action-github-pages@v1
```

### After

```yml
      - uses: retypeapp/action-build@v2.0.0-preview

      - uses: retypeapp/action-github-pages@v2.0.0-preview
```

After Retype `v2.0.0` is released, please change those two lines to use just `@v2`:


```yml
      - uses: retypeapp/action-build@v2

      - uses: retypeapp/action-github-pages@v2
```

Hope this helps.

**Comment by itsthejoker** [comment]
@geoffreymcgill Thank you very much! That was an easy fix.

@fabriciomurta Thank you for the context!

I'm very much looking forward to using this -- it looks great. Cheers!
