### ISSUE TITLE
Would the left sidebar collapsable?  

### ISSUE THREAD

**Issue by sevichee** [retypeapp/retype#293]
Sometimes I want to focus on the content and reduce distracting elements such as sidebars and navigation bar.

**Comment by geoffreymcgill** [comment]
I'm going to keep issue #40 in favour of this issue as the feature request has been made previously. Please feel free to add your comments to #40.

An alternative that might help now is to set `layout: central` in your page metadata. See [`layout`](https://retype.com/configuration/page/#layout) configuration. That layout will remove the left and right sidebars completely.

**Comment by sevichee** [comment]
Wow, Thank you!
