### ISSUE TITLE
Information request about the pro version

### ISSUE THREAD

**Issue by Liandriz** [retypeapp/retype#298]
Hi, tried and loved Retype, thought to use it to replace my actual wiki.  
I imported several pages, and saw there was a hard limit to 100 pages, and asked me to upgrade to the pro version.  
Not a problem, but where can i get the pro version atm please? 

Thanks for your answer, and for the project!

**Comment by geoffreymcgill** [comment]
Soon. 

If you need a trial key, please email me at geoff@object.net with the request and I'll send back a key to test with. In the email, please include the domain(s) or sub-domain(s) you need to publish to. The keys are associated to a domain or sub-domain.

**Comment by Liandriz** [comment]
Thanks for your help!
