### ISSUE TITLE
File names changed after `retype build`

### ISSUE THREAD

**Issue by SofieTorch** [retypeapp/retype#302]
I am combining Retype with another documentation generator from doc comments: Dartdoc.
Dartdoc generates .html files, which I am placing inside a `static` folder, but when I run a `retype build`, both locally and in github action, all the file names are converted to lowercase, so the redirection is broken.

### Original file names:
![image](https://user-images.githubusercontent.com/61905544/159099360-311e0800-0469-4d8c-8902-54520a0fabbf.png)

### After `retype build`:
![image](https://user-images.githubusercontent.com/61905544/159099421-5261c8ff-2573-4b20-9c78-b7383d7dcb09.png)

![image](https://user-images.githubusercontent.com/61905544/159099388-33d949df-4227-405e-b2a4-a144270651b0.png)

If there is some flag on retype.yaml or some command I could run after generating the docs to avoid this behaviour, please let me know :worried: .

**Comment by fabriciomurta** [comment]
Confirmed. Any static file's names will get their case changed once they are copied over to Retype's output folder. Thanks for the heads up! This wouldn't be a problem for hosting in case-insensitive filesystem/oses, but that's not the case for Mac and Linux, mostly.

**Comment by geoffreymcgill** [comment]
Hi @SofieTorch. Thanks for reporting this issue. The re-casing of the file names should not be happening. We are going to fix right away and will include the fix in the next release of Retype, which should be very soon.

At the moment, we do not have a work-around to avoid the problem.

**Comment by SofieTorch** [comment]
Thanks for the fast response ^^
Looking for a solution I came up with [this action](https://github.com/SofieTorch/find-and-lowercase-action) which acts as a patch.
Basically it receives a regex, and changes the matches to lowercase, so I'm using it with the pattern `<a href="([^"]+(\.html|#.+))">`
Just saying, in case someone else is facing this problem.

Hope it will be solved soon, thank you!

**Comment by geoffreymcgill** [comment]
We were not able to get this fix into the `v2.1` release, but we're working on it right now and as soon as it's ready, we will release `v2.2`. 

We are introducing a new project config called `generator.recase` where you can control how Retype recases file and folder names. Options will include `all` and `none`. Default is `all`.

If you do not want Retype to automatically recase file and folder names (to all lowercase), you will set `recase: none` in your `retype.yml` project configuration file.

```yml
generator:
  recase: none
```

Value | Description
--- | ---
`all` | All file and folder names are deployed in full lowercase. Default is `all`.
`none` | Retype will not change the case of any file or folder names.

**Comment by geoffreymcgill** [comment]
There was a change in `v2.1` that might affect you. Now by default, Retype will automatically deploy any `.html` or `.htm` files that is finds in your project `input` to the `output`. 

You can place `.html` files anywhere in your project and Retype will automatically copy those files to the generated website.

This new functionality even allows you to create a custom `index.html` home page for the website. Just add an `index.html` to the root of your project and remove the `readme.md`.

**Comment by fabriciomurta** [comment]
The setting is now avaliable as of [Retype v2.2.0](https://github.com/retypeapp/retype/releases/tag/v2.2.0)!

**Comment by geoffreymcgill** [comment]
Hi @SofieTorch. If you upgrade to Retype `v2.2`, there is a new `recase` project configuration that should work for your scenario. 

For your project, within your `retype.yml` file, add the following configuration:

```yml
generator:
  recase: none
```

https://retype.com/configuration/project/#recase

Hope this helps.
