### ISSUE TITLE
Accent chars causing querySelector js error

### ISSUE THREAD

**Issue by slimooo** [retypeapp/retype#32]
Hello,

an other bug : https://www.loom.com/share/77c0297529314d34a4b9bd3fe985954a

Only H1 link without french accent (é,è,à) work !

**Comment by geoffreymcgill** [comment]
Nice find. We are investigating and will fix right away.

**Comment by geoffreymcgill** [comment]
This defect has been fixed and will be included in the `v1.7.0` release.
