### ISSUE TITLE
When linking to a file, replace file-name.md with the pretty file name that would be shown on the sidebar

### ISSUE THREAD

**Issue by u9g** [retypeapp/retype#320]
It would be nice to make the links to other pages look better. Here's how a link to another page looks in gitbook: ![gitbook hotlink](https://i.imgur.com/uoZpU8s.png) and here's how it looks in retype: ![retype hotlink](https://i.imgur.com/8rLQk9t.png)

**Comment by u9g** [comment]
nvm, realized this already exists

**Comment by geoffreymcgill** [comment]
For future reference if anyone is reading this thread, you can customize the text of the link using Markdown hyperlink syntax. The following sample demonstrates:

```md
,take a look at [Looking at a player](looking-at-a-player.md)
```

For hyperlinks, Retype does not automatically add the friendly name to the hyperlink.

Hope this helps.

**Comment by u9g** [comment]
That hyperlink method doesnt work, I tried it here: https://raw.githubusercontent.com/u9g/mineflayer-docs/main/inventory/drop-items-in-bots-inventory.md , but on the rendered page, it doesn’t turn out formatted with the comma: https://u9g.github.io/mineflayer-docs/inventory/drop-items-in-bots-inventory/

**Comment by geoffreymcgill** [comment]
It looks like your `looking-at-a-player.md` file is in a different folder, so you just need to specify the path to that folder. 

I believe the corrected link should be:

```md
[Looking at a player](/common-tasks/looking-at-a-player.md)
```

Hope this helps.
