### ISSUE TITLE
How does templating work?

### ISSUE THREAD

**Issue by sladkoff** [retypeapp/retype#326]
Hi, I have some questions. 

I'm playing around with retype and I'm trying to use variables. 

I found the `templating.enabled` configuration option: https://retype.com/configuration/project/#enabled-1

I can't seem to find any examples for how to use the "Retype Templating Engine"?

I see that there's also the `templating.liquid` flag.

Could you point me to a documentation on the usage of these templating features?

I'm specifically interested in defining global variables and re-using them across Markdown files. Is this possible?

**Comment by geoffreymcgill** [comment]
We are way behind with documenting the new content templating functionality.

> I'm specifically interested in defining global variables and re-using them across Markdown files. Is this possible?

Yes, possible and simple. 

You can add your custom variables into your projects `retype.yml` file under the `data` config. Then reference them anywhere within your `.md` documents.

Here is a basic example where a custom `msg` variable is defined, then used within a page:

**retype.yml**
```yml
data:
  msg: "Hello, World"
```
**sample.md**
```md
{{ msg }}
```

<img width="139" alt="Screen Shot 2022-05-06 at 12 27 06 PM" src="https://user-images.githubusercontent.com/62210/167197376-f36d50b1-37d9-4ec5-8a66-cfcee39a444d.png">

You can also define custom `data` variables within the `.md` page metadata if you want the variables scoped to only the page.

Retype uses the Scriban templating engine and the entire feature set is supported. See their docs for the full scope of what is possible:

https://github.com/scriban/scriban/blob/master/doc/language.md

Hope this helps.

**Comment by sladkoff** [comment]
This is just what I was looking for. Thank you!
