### ISSUE TITLE
Static folder visible in nav menu

### ISSUE THREAD

**Issue by davidsteelebrady** [retypeapp/retype#339]
I'm sure i'm doing something daft but my static folder always appears inside o fthe navigation pane.
Do I need to explicity configure retype.yml somehow, looked through the docs and this repo and couldnt see anything specific.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/76475855/173444235-05df715c-767a-4900-bcff-f8eb87ed3e57.png">

**Comment by geoffreymcgill** [comment]
Hi @davidsteelebrady, 

Do you have any `.md` files in that folder?

If yes, Retype will treat those as any other content page and create a navigation path to the pages. You can explicitly hide and `.md` files in that folder several different ways:

1. Prefix the file name with an `_` underscore. 
2. Set `visibility: hidden` in the page metadata, see [`visibility`](https://retype.com/configuration/page/#visibility) docs.
3. Configure and [`exclude`](https://retype.com/configuration/project/#exclude) pattern such as `exclude: [ "/static/*.md" ]`

If no, do those folders contain any file types that are not in the following list?

```
*.ai
*.bmp
*.eps
*.gif
*.heif
*.htm
*.html
*.jpeg
*.jpg
*.pdf
*.png
*.svg
*.tiff
*.txt
*.webp
*.zip
```

Hope this helps.

**Comment by davidsteelebrady** [comment]
Was exactly the problem, thanks @geoffreymcgill
