### ISSUE TITLE
Adding support for Matomo Analytics

### ISSUE THREAD

**Issue by hypherionmc** [retypeapp/retype#351]
Is there a possibility you could add support for Matomo Analytics (both self hosted or cloud)?

If not, is there a way to do this myself? It's a lighter alternative to Plausible which can run on normal web hosting and doesn't need docker.

More info here: https://matomo.org/

**Comment by geoffreymcgill** [comment]
You can add any custom HTML into the `<head>` of the document using the `_includes/head.html` file. More details available at the following links:

https://github.com/retypeapp/retype/discussions/272#discussioncomment-2879272
https://github.com/retypeapp/retype/discussions/282#discussioncomment-2343005

Hope this helps.

**Comment by geoffreymcgill** [comment]
> I was scared to upgrade cause of the the license, and the amount of pages we have on the site

The same 100 page limit was in `v1.x`, just there wasn't an option to upgrade to 1000 pages with Pro until the `v2.x` release.

If you're hosting your website on `github.io` or `gitlab.io`, we're thinking of making a new free _open source_ license with a 1000 page limit. The license would still actually allow for commercial websites, but would need to hosted on either GitHub or GitLab Pages using their default `gitlab.io` or `gitlab.io` domains.
