### ISSUE TITLE
_includes/head.html not included on every page

### ISSUE THREAD

**Issue by enceladus** [retypeapp/retype#359]
I am using `_includes/head.html` for custom styling, but it is only included on the first page refresh, and disappears once navigating to any other page via a click in the sidebar. Any idea why this would be happening?

**Comment by geoffreymcgill** [comment]
I suspect the web browser would just temporarily caching the pages and would clear up automatically with a hard refresh or if a little time passes.

Closing this issue, although we will certainly reopen if additional details are provided and we can reproduce the issue.
