### ISSUE TITLE
Add ability to remove folders from front-end hierarchy.

### ISSUE THREAD

**Issue by AGaiki** [retypeapp/retype#36]
Hey again! One feature I'd really like to see is the ability to remove folders from the front-end hierarchy. The current way is something like this:

```
|-- /folder
    |-- /folder2
        |-- sample.md
```
It will also show that way on the deployment as well. While that is useful, that method quickly falls apart when you attempt to organize files and images into folders. Say in a folder, you have this structure:
```
|-- /Example
    |-- /ExampleFolder
        |-- sample.md
        |-- image.png
    |-- /ExampleFolder2
        |-- sample2.md
        |-- image.png
```
When viewing the website, it will create two subfolders in the `Example` folder, `ExampleFolder` and `ExampleFolder2`. This creates unneeded levels within the site. There could be an option in the configuration in each Markdown file to ignore the immediate folder hierarchy and to serve it directly under the parent folder (hopefully that made sense).

**Comment by geoffreymcgill** [comment]
Your scenario can be supported by renaming `sample.md` to `readme.md` or `index.md`

The same technique would apply to `ExampleFolder2/sample2.md` which would be renamed to `ExampleFolder2/readme.md`.

I could see a potential use-case for having a page metadata config that allows for even more flexibility in where the page is placed in the navigation, although that does also seem like it might be adding unnecessary complexity. I'll put some thought into it.

Anyways, for your scenario, renaming both `sample.md` and `sample2.md` to `readme.md` or `index.md` will support your requirements. 

Hope this helps.

**Comment by AGaiki** [comment]
It helped! I also figured out that if I wanted multiple articles on the root level of a folder (not THE root folder of the Retype deployment), I just need to create folders and name each article `index.md`. I'm gonna close this ticket cause my feature request is already in Retype v1.6 in some regard. Thanks for your help!
