### ISSUE TITLE
The panel title get totally skipped from the index

### ISSUE THREAD

**Issue by ddnexus** [retypeapp/retype#363]
```
==- MyImportantWord
...
===
```

If you search "MyImportantWord" that is only present in a panel title, you get a "Sorry, no results found." 😕

**Comment by geoffreymcgill** [comment]
Good point. We should be able to get the Panel title added to the search index. I'll take a look and we will try to include in the next Retype release.

**Comment by geoffreymcgill** [comment]
As of Retype v3.0, the Panel titles are now added to the search index. 

Hope this helps.
