### ISSUE TITLE
SSTI in code blocks and inline code?

### ISSUE THREAD

**Issue by caueb** [retypeapp/retype#366]
It seems that there is a server-side template injection in the code block/inline code.

When I try to add a code block or inline code like `{{ 7*7 }}` it actually renders `49`.
Or if I add `{{ 7*'7' }}` it renders as `7777777`.

Expected behavior:
I use retype to take notes and document penetration testing techniques, and need to be able to create code blocks or inline code such as the above mentioned.

**Comment by geoffreymcgill** [comment]
Yes, those code snippets are getting picked up by the Templating engine. There are a couple options:

### Option 1

Disable templating within your project by adding the following config to your `retype.yml` project file.

```yml
templating:
    enabled: false
```

### Option 2

Escape those `{{ }}` code samples by wrapping with `{% %}`.

Your sample would be revised to the following:

```md
Not-escaped
{{ 7*7 }}

Escaped
{%{{ 7*7 }}%}
```

Hope this helps.

**Comment by caueb** [comment]
Thank you @geoffreymcgill, that solves my problem. Feel free to close the issue.
