### ISSUE TITLE
"retype watch" throws an error.

### ISSUE THREAD

**Issue by AGaiki** [retypeapp/retype#37]
I've been trying to use Retype on Windows today, and I run into this error: 
![image](https://user-images.githubusercontent.com/58378384/122624015-409fa780-d053-11eb-92f1-581b999f1b70.png)
For reference, I am running 64-bit Windows 10 Pro.

I have tried uninstalling and reinstalling Retype.

**Comment by geoffreymcgill** [comment]
Thanks for the report. We will try to reproduce the environment locally. 

Questions:
1. What version does the command `retype --version` return?
2. What command did you use to install Retype?
3. Do you have the [`dotnet`](https://dotnet.microsoft.com/download/dotnet-core) SDK installed on this machine? or NPM? or Yarn?

**Comment by geoffreymcgill** [comment]
The file throwing this error is not a Retype file:

```
C:\Users\adity\AppData\Roaming\npm\node_modules\retypeapp\platform.js
```

You might have missed including the ` --global` flag when installing using NPM. Try to install Retype using the following command:

```
npm install retypeapp --global
```

Detailed installation instructions are available at https://retype.com/guides/getting-started/#install.

Hope this helps.

**Comment by AGaiki** [comment]
I reinstalled Retype using the `--global` flag. It's throwing the same error.

**Comment by geoffreymcgill** [comment]
It looks like Retype was added to your NPM project and it's likely configured somehow within your projects `package.json` file. Try to uninstall from the NPM project using `npm uninstall retypeapp`.

If that still doesn't solve the issue, try the following three steps:

```
npm uninstall retypeapp
npm uninstall retypeapp --global
npm install retypeapp --global
retype watch
```

Hope this helps.

**Comment by AGaiki** [comment]
Unfortunately, those steps didn't seem to help. However, a fresh install of NodeJS seemed to fix it. Thanks for your help!

**Comment by fabriciomurta** [comment]
Retype is built for 64-bit platforms (linux, win, mac) and you had 32-bit NodeJS installed, that's why it didn't work.
