### ISSUE TITLE
Allow usage of icons for lists

### ISSUE THREAD

**Issue by xyeLz** [retypeapp/retype#370]
I was hoping it would be possible to use the :star: or :star-icon: emoji/icon as my bullet for lists instead of the built-in checkbox or dot.

**Comment by geoffreymcgill** [comment]
This is possible using a little custom CSS. 

```html
<style>
ul.stars {
  list-style: "⭐  ";
  list-style-position: outside;
}
ul.stars ul li {
  list-style-type: circle;
}
</style>
{ .stars }
- Item 1
- Item 2
- Item 3
```

<img width="241" alt="Screen Shot 2022-08-04 at 11 23 54 AM" src="https://user-images.githubusercontent.com/62210/182913118-460111f3-376c-4e26-9387-96874de6b91e.png">

The content of that `<style>` block could also be moved out of the page and included site wide by adding to the `_includes/head.html` file.

```html
<!-- include this snippet into the file _includes/head.html -->
<style>
ul.stars {
  list-style: "⭐  ";
  list-style-position: outside;
}
ul.stars ul li {
  list-style-type: circle;
}
</style>
```

The list syntax on the page would then just be the following:

```md
{ .stars }
- Item 1
- Item 2
- Item 3
```

The above custom style could also be inlined, as the following sample demonstrates:

```
{ style="list-style: '⭐  ';list-style-position: outside; li { list-style-type: circle; } " }
- Item 1
- Item 2
- Item 3
```

<img width="242" alt="Screen Shot 2022-08-04 at 11 24 15 AM" src="https://user-images.githubusercontent.com/62210/182913012-293fab19-3af9-40c4-aad2-e95004d31195.png">

Hope this helps.

**Comment by geoffreymcgill** [comment]
Please see issue #603 and the following comment for several other samples on how to create icon lists, see

https://github.com/retypeapp/retype/issues/603#issuecomment-1692740146

Hope this helps.
