### ISSUE TITLE
Automatically scroll ToC with page content

### ISSUE THREAD

**Issue by xyeLz** [retypeapp/retype#375]
I noticed that when reviewing some content on the primary Retype website (https://retype.com/configuration/project/#server), when I would use my mouse wheel to scroll up to the top while reading content, the ToC didn't scroll with me. It _did_ dynamically update the content I was reading, but once I got to the top of the page, I didn't know where I was at since the ToC didn't scroll with me. I use Edge on Windows 11.

This is not a big deal whatsoever and would definitely be a low priority feature request. I'm not even sure if any of the other major wikis support this type of platform but it would be a cool option to allow the user to select which they'd prefer.

**Comment by geoffreymcgill** [comment]
Hi @xyeLz. Thanks for the report. We will run some tests on Edge and see if we can figure out what's going wrong. From what I can tell, this only seems to be an issue with Edge, which is somewhat strange.

**Comment by xyeLz** [comment]
Hi @geoffreymcgill. I may have explained this poorly. This is also reproducible in Firefox. I attached some screenshots to try and help explain further.

In this image, everything is working as intended. I am navigating the page with my mouse scroll wheel and the right ToC is scrolling along with me:

![left-is-fine](https://user-images.githubusercontent.com/24688509/183939984-e0117499-1fa5-49a1-8f0c-c5c7123344b5.png)

In this screenshot, you'll see I continued scrolling down the page, and while the ToC highlight _did_ scroll with me, it is beginning to go off the screen:

![toc-missing](https://user-images.githubusercontent.com/24688509/183940117-ea351299-dca0-4bcd-8747-34093f76b005.png)

My thought was to also scroll the ToC automatically if someone is viewing content that would trigger that specific ToC anchor to be highlighted:

![auto-scroll-this](https://user-images.githubusercontent.com/24688509/183940444-159456c1-a6ee-4b88-9406-74fdb384c6cf.png)

**Comment by geoffreymcgill** [comment]
Thanks for the additional details. I understand the scenario now. 

Any chance you could link me to any website or app out on the internet that performs a repositioning of the sidebar table-of-contents items when this type of long scroll happens? I'd just like to see what this feels like and see how others might have accomplished this interface sequencing.

I guess the new items at the bottom of the TOC would just need to be scrolled into view on the right. Maybe that wouldn't be too difficult to make work. Although, seems like every time I say that, the task ends of taking 10x my initial time estimate.

**Comment by dt192** [comment]
Hi, Just came to report this bug too.

[mkdocs](https://squidfunk.github.io/mkdocs-material/changelog/) seems to handle it fine in Edge.

**Comment by geoffreymcgill** [comment]
We have improved the ToC to ensure the active items are always scrolled into view. 

The new functionality will be included in the upcoming Retype v3.4 release.

**Comment by geoffreymcgill** [comment]
Retype v3.4.0 is now available. 

https://retype.com/changelog/

**Comment by geoffreymcgill** [comment]
Anybody here test the new functionality of automatically moving the current ToC items into view? What do you think?

**Comment by xyeLz** [comment]
Confirmed this actually works beautifully now. Thanks for the attention to this.
