### ISSUE TITLE
Implement easy method for opening regular links in a new tab

### ISSUE THREAD

**Issue by xyeLz** [retypeapp/retype#387]
I see the ability to use target="blank" for certain components such as buttons, but I haven't found an easy method of implementing this for [regular links](https://alukos.com). If this capability doesn't exist, I would definitely recommend it.

**Comment by geoffreymcgill** [comment]
Within Markdown, there is no syntax for adding `target="_blank"`, but within Retype you can define an attribute override on the hyperlink element. The following sample demonstrates:

```md
[regular links](https://alukos.com/){ target="_blank" }
```

The above Markdown will be translated into the following HTML element:

```html
<a href="https://alukos.com/" target="_blank">regular links</a>
```

Hope this helps.
