### ISSUE TITLE
Can tags be added anywhere?

### ISSUE THREAD

**Issue by xyeLz** [retypeapp/retype#392]
Is there any way to manually add a tag somewhere without requiring the use of a header or panel or other component? For example, on https://retypetest.pages.dev/guidance/cis-controls I am creating a "References" section. Within the body, I am creating links that will link to items in the reference section; however, I do not want use `###### 1 referencelink.com` simply to link a reference. Specifically, I would really like to use a numbered list since they keep the content consolidated. Is there any way to create anchors in such a way? For example:

```
## References

1. {#https://www.sans.org/blog/cis-controls-v8/}
```

Or:

```
## References

1. <a name="https://www.sans.org/blog/cis-controls-v8/"></a>
```

I suspect I won't be able to use the `1.` as the anchor since that would be the start of the bullet point/numbered list, but that would be ideal if it could be used and still remain an indented list.

**Comment by geoffreymcgill** [comment]
I don't believe there is any pure Markdown syntax that would render as a named anchor point, but I did get the following sample to work with using a `<span>` tag. 

```md
## Sample

See [item1](#item1)

## References

1. https://www.sans.org/blog/cis-controls-v8/<span id="item1"></span>
```

The `<span>` could be before or after the hyperlink. 

Hope this helps.

**Comment by xyeLz** [comment]
That did the trick! Thank you! I would close this, but figured I'd leave it open for you to close at leisure, or transform into a feature request if that's something you plan to implement in a component down the road.

**Comment by xyeLz** [comment]
Actually, it seems like this may have caused some unusual behavior. For example, my pages occasionally lose their formatting now. Additionally, the logo at the top left of the page displays after a refresh and then disappears.

**Comment by geoffreymcgill** [comment]
Adding the `<span>` element named anchors seems simple enough if you would like to work-around the limitations of Markdown.

**Comment by geoffreymcgill** [comment]
> Actually, it seems like this may have caused some unusual behavior. For example, my pages occasionally lose their formatting now. Additionally, the logo at the top left of the page displays after a refresh and then disappears.

Please triple check that you have closed all open `<span>` tags. Each opening `<span>` must have a closing `</span>` tag. 

Hope this helps.

**Comment by xyeLz** [comment]
My apologies. This was not an issue with the <span>. It was related to another change made simultaneously. I will create an issue report.
