### ISSUE TITLE
Implement ability for links to panels to auto-open the panel

### ISSUE THREAD

**Issue by xyeLz** [retypeapp/retype#401]
As it stands currently, if someone uses a link from a _separate_ page, if that link is to a panel, it loads the page and then automatically expands the panel. This behavior is different if the panel is within the same page. If the panel is on the same page, it links to the panel but does not automatically open it. It would be great if this would automatically expand the panel.

Alternatively, giving the user the option as to whether they want the panel expanded or not, either from a remote destination or locally, perhaps at the page level, would be great.

**Comment by geoffreymcgill** [comment]
This enhancement has been made and it will be included in the next release of Retype. 

When Panels are linked to within the same Page, the Panel will now be automatically expanded. 

Hope this helps.
