### ISSUE TITLE
right sidebar highlights wrong current title

### ISSUE THREAD

**Issue by noraj** [retypeapp/retype#41]
The right sidebar shows / highlights the wrong current title level

eg. https://retype.com/configuration/project/#colors

![image](https://user-images.githubusercontent.com/16578570/122804122-ca57ab00-d2c7-11eb-8e28-08afb2d16bf1.png)

Version: v1.6

## See also

- #134

**Comment by geoffreymcgill** [comment]
yep, this is a defect. I noticed this recently as well. 

It's a priority issue for use to fix and we're going to try and fix right away.

**Comment by sapphyrus** [comment]
> yep, this is a defect. I noticed this recently as well.
> 
> It's a priority issue for use to fix and we're going to try and fix right away.

Any news on this?

**Comment by geoffreymcgill** [comment]
We have this working correctly now and the new functionality will be included in the next release. Retype now highlights the correct item in the table of contents and the performance has been significantly improved.

To upgrade, no changes to your project will be required, other than using the next public release, which likely will be `Retype v2.0`. No official release date is available, but we're working hard to get `v2.0` wrapped up as fast as we can.

Hope this helps.
