### ISSUE TITLE
Octicon "copilot" icon does not load

### ISSUE THREAD

**Issue by nembal** [retypeapp/retype#412]
We are trying to use the [copilot](https://github.com/primer/octicons/blob/main/icons/copilot-16.svg) icon from the Octicon database, but it does not load on our retype. 
All other octicon works fine.

**Comment by geoffreymcgill** [comment]
Looks like the `copilot` icon was added recently to the Octicon library and has not made it into a public release of Retype. When I test the upcoming Retype v3.0 release, the icon is supported. 

```md
## Sample

:icon-copilot:
```

<img width="182" alt="Screen Shot 2022-08-31 at 10 54 18 AM" src="https://user-images.githubusercontent.com/62210/187735626-15399534-4819-41e9-8245-f40e3f464ec9.png">

We don't have an official release date for the Retype `v3.0` but we're working on it right now and it will be the next public release.

**Comment by geoffreymcgill** [comment]
I'm going to mark this as closed, but the `copilot` icon will not be included until the Retype `v3.0` release.
