### ISSUE TITLE
Mermaidjs seems to be outdated

### ISSUE THREAD

**Issue by aleks3fs** [retypeapp/retype#414]
When using mermaid charts in retype, I cannot use new chart types like gitgraph.

It seems like mermaid version is 8.13.10, latest is 9.1.6.

Could we get an upgrade?

**Comment by geoffreymcgill** [comment]
Thanks for letting us know. We do not have an automated process for updating the Mermaid library, so this was missed in the recent releases. 

I will ensure the Mermaid library is upgraded for the next Retype release, which will be `v3.0`. At the moment, we do not have a release date for Retype `v3.0`, but we are working on it and it will be the next release.

**Comment by aleks3fs** [comment]
Great! Amazing, thanks 🙏.

I'm wondering would it make sense to expose version of mermaidjs (and maybe other libs) as config? That way customers could use whatever is packages originally, or try their preferred one.

**Comment by ChuckMN** [comment]
@geoffreymcgill any sneak peak on when the 3.0 release will be? I have some exciting new graphs I would like to include leveraging the latest version of mermaid.

Thanks for making an awesome resource that helps make the world a better place!

**Comment by maulemon** [comment]
Hi @geoffreymcgill, it's been a while now and we are seeing inconsistencies in how Mermaid renders directly on GitHub vs version used by retype. Have you got any estimated timeline for releasing `v3.0` ?

**Comment by geoffreymcgill** [comment]
We have updated Retype to Mermaid 9.3.0 and the update will be available in the upcoming Retype v3.0 release. No firm release date at the moment, but we are making good progress and want to get it released ASAP. Shouldn't be long now.

The latest public release of Mermaid is actually [10.0.2](https://www.npmjs.com/package/mermaid) but we (and [others](https://github.com/mermaid-js/mermaid/issues/4203)) have run into an issue with how huge the new Mermaid build is. Our install went from ~1 MB to ~2.5 MB of minified JS code for Mermaid. Others are reporting much larger increases in size. 

We don't know what's going on with the Mermaid 10.0.2 release, so we're avoiding for now. Retype v3.0 will ship with Mermaid v9.3. 

Hope this helps.
