### ISSUE TITLE
Partial template issue

### ISSUE THREAD

**Issue by dipbhi** [retypeapp/retype#417]
I am trying to use partial templates as mentioned in one of the discussions. 

retype version: 2.4.0

-----

Here is what I did:
1. Created `custom-alert.md` at root with below content
```
!!! {{ title | string.capitalize }}
{{ text }}
!!!
```

2. Created `reuse.md` at root with below content
```
---
custom-text: This is custom alert message defined in a variable.
custom-title: Holy cow!
---
{{ custom-alert text="{{ custom-text }}" title="{{ custom-title }}" }}
```

-----
On page http://localhost:5000/reuse/

Expected result: 
![image](https://user-images.githubusercontent.com/12301512/188685742-f22cdf74-a177-49f7-9ca0-bea03f682295.png)

Actual result:
![image](https://user-images.githubusercontent.com/12301512/188685972-e92b916f-c48a-45f3-8fc6-71033c21f3dc.png)

**Comment by geoffreymcgill** [comment]
There are several things with the templating that are not working as I expected. I am investigating but need more time. I should have some answers soon.

**Comment by dipbhi** [comment]
Hi @geoffreymcgill,

Are you still working on this? Reusability would be very helpful as the docs grow.

**Comment by dipbhi** [comment]
Worked perfectly. Thank you.

P.S.: I believe you meant `/_includes/` folder (starting with underscore).

**Comment by granicz** [comment]
So these named variables are assumed to contain strings literals, is there a plan to enable them to take (multi-line) markdown/retype content?

**Comment by geoffreymcgill** [comment]
@granicz You can also add multiline strings that contain markdown. The following sample demonstrates:

```md
---
data:
  text: "This is custom :smile: alert 
        message defined in a variable.
        The msg is spread across multiple lines
        and contains **Markdown** syntax."
---
# Sample

!!! Custom Alert
{{ text }}
!!!
```

<img width="797" alt="Screenshot 2023-01-07 at 11 18 18 AM" src="https://user-images.githubusercontent.com/62210/211145450-c8b89623-9865-406d-b2c9-fa959c09195f.png">


Hope this helps.

**Comment by geoffreymcgill** [comment]
Passing named variables to the `include` is supported. Here is a sample demonstrating how to pass values into an `include` to create custom Alert component.

#### sample-page.md

```md
{{ include "my-alert" title:"Hello" text:"Is this working?" }}
```

#### _includes/my-alert.md

```md
!!! {{ $.title | string.capitalize }}
{{ $.text }}
!!!
```

The key is that the `title` variable needs to be referenced from the `$`, such as `$.title`.

All data types work, including strings, boolean, array, objects, etc. 

Hope this helps.
