### ISSUE TITLE
Multi Language Support Plan?

### ISSUE THREAD

**Issue by jihoony** [retypeapp/retype#424]
Dear Team,

I'm using retype very useful.

I want to know planning for multi language search support.
and please support korean language for search.

Thanks.

**Comment by geoffreymcgill** [comment]
Korean will be supported in the upcoming Retype v3.0 release.

Once v3.0 is release, you can set `locale: ko` in your `retype.yml` to enable.

The translation file is available at:
https://github.com/retypeapp/retype-translations/blob/main/src/UserInterface.ko.resx

If you would like to revise the above file, please see the documentation at:
https://github.com/retypeapp/retype-translations or,
https://retypeapp.github.io/retype-translations/

Hope this helps.
