### ISSUE TITLE
Mustaches disappear from code blocks and inline code

### ISSUE THREAD

**Issue by joonaspaakko** [retypeapp/retype#426]
Retype version: 2.4.0. I thought this wasn't always the case, but I tried to downgrade and it didn't seem to have any effect...

- - - - - 
### This:
{{ example }}

```
  {{ example }}
```
### Becomes:
![](https://user-images.githubusercontent.com/1164476/194861867-be1980c0-9483-4923-85e3-76e53f33654d.png)

- - - - - -

### This:
{{ example }.}

```
  {{ example }.}
```
### Becomes: 
![](https://user-images.githubusercontent.com/1164476/194861898-ddb2deab-43fa-4827-9551-c38328ad5cdc.png)

**Comment by geoffreymcgill** [comment]
The `{{ example }}` is getting caught be the templating engine. There are four options.

### 1. Disable Templating project wide

Add the following config to your `retype.yml` file:

```yml
templating:
  enabled: false
```

### 2. Disable Templating on the Page

Add the following config to your `.md` page metadata section:

```yml
---
templating: false
---
# My sample page
```

### 3. Escape that specific snippet

Wrap the snippet with templating `{%{` and `}%}` escape tags. 

~~~
```
{%{{{ example }}}%}
```
~~~

### 4. Escape the entire code block

Wrap the templating escape tags around the entire code block.

~~~
{%{
```
{{ example }}
```
}%}
~~~

Any one of the above options should solve the issue.

Hope this helps.

**Comment by joonaspaakko** [comment]
Ah right. It didn't occur to me that it might be a thing... I'm not using it so I disabled it.

**Comment by Kreyu** [comment]
For future reference: if your project is using liquid templating:

```
templating:
  liquid: true
```

wrap the codeblock in the `{% raw %}` tag:
``````
{% raw %}
```
{{ example }}
```
{% endraw %}
``````
