### ISSUE TITLE
The Search function don't work on my sites

### ISSUE THREAD

**Issue by mcpeapsUnterstrichHD** [retypeapp/retype#429]
[Page 1](https://bit.ly/comboomPunkTsucht-GHP)
[Page 1 GH repo](https://github.com/comboomPunkTsucht/comboom.sucht-BLOG)

[Page 2](https://bit.ly/ITA12DocOSZimt)
[Page 2 GH repo](https://github.com/comboomPunkTsucht/OSZ_ITA12_Doc)

**Comment by geoffreymcgill** [comment]
Looks like the `url` config in your `retype.yml` file might be wrong:

https://github.com/comboomPunkTsucht/comboom.sucht-BLOG/blob/main/retype.yml#L3

Try setting to the following:

```yml
url: https://comboompunktsucht.github.io/comboom.sucht-BLOG/
```

Hope this helps.

**Comment by mcpeapsUnterstrichHD** [comment]
have i
