### ISSUE TITLE
Unable to activate google analytics on web page

### ISSUE THREAD

**Issue by beyond9thousand** [retypeapp/retype#442]
[Referred to this specific section and triple checked everything](https://retype.com/configuration/project/#googleanalytics)

Google analytics doesn't seem to be picking up any data whatsoever and seems as if the website doesn't have the tracking installed properly.

[Website](https://beyond9thousand.github.io/meta/)
[Repository](https://github.com/beyond9thousand/meta/blob/main/retype.yml)

**Comment by geoffreymcgill** [comment]
We are running Google Analytics on retype.com and it appears to be collecting data correctly.

Is Google Analytics giving you a specific error message or any other kind of message stating your tracking code is not installed correctly? If yes, can you share that msg here?

**Comment by beyond9thousand** [comment]
![Screenshot_2022-11-16-05-39-23-10_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/77363063/202051420-94247289-3442-469f-88a0-1f18d4a34384.jpg)

![Screenshot_2022-11-16-05-39-55-68_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/77363063/202051625-92647a87-6359-4918-b591-5702601025db.jpg)

This is all I've been able to gather

**Comment by geoffreymcgill** [comment]
Everything looks correct. 

Can you click on the `Get tagging instructions` button and paste here the snippet of code that is required to be on your website? It should look similar to the following:

```html
<script async src="https://www.googletagmanager.com/gtag/js?id=G-MCZCBE4E9S"></script>
<script>window.dataLayer = window.dataLayer \|\| [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-MCZCBE4E9S');</script>
```

**Comment by beyond9thousand** [comment]
**UPDATE:** it seems to have started working. Is there a wait period from the time the website has first been launched for analytics to be activated? Or when the ID is first assigned etc?

**Comment by geoffreymcgill** [comment]
> Is there a wait period from the time the website has first been launched for analytics to be activated?

That would be determined by Google. I'm not sure when Google starts recording hits, although from my experience, once the Google Analytics code is live/public, the Google Analytics dashboard starts recording hits right away.

**Comment by beyond9thousand** [comment]
I see, thanks for the prompt response anyway!
