### ISSUE TITLE
Syntax highlighting documentation

### ISSUE THREAD

**Issue by noraj** [retypeapp/retype#445]
What is the library used for [syntax highlighting](https://github.com/retypeapp/retype/blob/main/components/code-block.md#syntax-highlighting) and what is the list of supported languages and short codes?

It's especially painful to have to guess what's supported or not since it seems the library is quite limited (see #446).

**Comment by geoffreymcgill** [comment]
Retype uses [PrismJS](https://prismjs.com/) for syntax highlighting. 

All PrismJS language modules are dynamically loaded as required and all Prism [supported languages](https://prismjs.com/#supported-languages) are supported by Retype.

I will add a comment to the [code block](https://retype.com/components/code-block/) component docs noting the use of PrismJS as the syntax highlighting library within Retype.

Hope this helps
