### ISSUE TITLE
Syntax highlighting corrupts Terraform (HCL) code

### ISSUE THREAD

**Issue by ronald8192** [retypeapp/retype#457]
In the markdown file:

    ```hcl
    resource "aws_s3_bucket" "b" {
      bucket = "my-tf-test-bucket"
    
      tags = {
        Name        = "My bucket"
        Environment = "Dev"
      }
    }
    
    resource "aws_s3_bucket_acl" "example" {
      bucket = aws_s3_bucket.b.id
      acl    = "private"
    }
    ```

Generated:
![image](https://user-images.githubusercontent.com/5982132/204956324-c9674787-98ad-456e-a089-45a0e7366cd1.png)

Works on [https://prismjs.com/test.html#language=hcl](https://prismjs.com/test.html#language=hcl)

![image](https://user-images.githubusercontent.com/5982132/204956399-ef586cf9-a868-408b-a85d-48f7bffafd58.png)

Maybe related: issue #446

**Comment by geoffreymcgill** [comment]
Confirmed. Looks like an issue with the `hcl` parser in PrismJS. When Retype is updated to the latest release, that should fix the defect.

**Comment by ronald8192** [comment]
I am using v3.5.0 but still having the same issue.
