### ISSUE TITLE
Welcome Page Deleting

### ISSUE THREAD

**Issue by VTenoris** [retypeapp/retype#461]
Hello, I can't find how to delete Welcome page in the picture. Can anyone help me?
![image](https://user-images.githubusercontent.com/105542754/206858903-68bb8c55-eea3-4d08-a052-39911b5f8507.png)

**Comment by geoffreymcgill** [comment]
Adding a `readme.md`, `default.md`, or `index.md` to the root folder of your project will then become your default home page, and that will replace the default `Welcome` page. 

Hope this helps.

**Comment by Tirarex** [comment]
Is `Welcome.md` is more suitable replace for **welcome** page ?

**Comment by geoffreymcgill** [comment]
As of the upcoming Retype v3.0, we have added support for `welcome.md` in the root of the project. Adding a `welcome.md` file will work the same as the other default pages, although will take the lowest precedence. 

The order of precedence is:

1. `index.md`
2. `default.md`
3. `readme.md`
4. `welcome.md`

If a `index.md` and a `welcome.md` file are in the root folder, the `index.md` file will be used as the default home page. The `welcome.md` file will create a `/welcome` page. 

Hope this helps.
