### ISSUE TITLE
Icon command-palette doesn't work

### ISSUE THREAD

**Issue by mariusrak** [retypeapp/retype#463]
Hi, one icon - "command-palette" from octicos doesn't work. Other works just fine.
This is beginning of my page file.

```md
---
order: 90
icon: command-palette
---
```

I didn't test all the icons, but all which I used till now works except this one.

**Comment by geoffreymcgill** [comment]
These icons will be supported with the next release of Retype. 

The Octicons are a few releases ahead of the version we have included in Retype, so some of the newer icons are not available in Retype.
