### ISSUE TITLE
Project Config: Show logo only

### ISSUE THREAD

**Issue by neilwoodwards** [retypeapp/retype#480]
How can I display the logo only? When I have `title: name` and `logo: path` it shows the logo with the title. But when I remove the title the logo disappears.

**Comment by geoffreymcgill** [comment]
I was not able to reproduce the issue you describe. 

The retype.com project itself uses only a `logo` with no `title`, see

https://github.com/retypeapp/retype/blob/main/retype.yml#L5-L8
