### ISSUE TITLE
Using Type in Android

### ISSUE THREAD

**Issue by juanppdev** [retypeapp/retype#498]
Good afternoon, I wanted to try Retype on my Android tablet, since this is my working medium so when installing Retype with npm I get this:

android.arm64 Node.js environment is not supported by Retype.
Supported Node.js environments:

win32.x86
win32.x64
linux.x64
darwin.x64
I am using the termux terminal and as I said I wanted to try it

**Comment by geoffreymcgill** [comment]
Hi @fomundifr. Our current installer platform does not support this environment. It's something we can look into for a future release, but for now, I don't think installing Retype on an Android tablet is possible.

**Comment by geoffreymcgill** [comment]
Installing on Android Tablet might work with the upcoming Retype v3.0 release. We don't have a specific release date, but we're working on it.
