### ISSUE TITLE
Twig symbols not ignored

### ISSUE THREAD

**Issue by AlexKatyukov** [retypeapp/retype#499]
Hi!

I'd like to insert base info about twig to Retype documentation, but I got a problem that twig symbols are not ignored and Retype trying to find variables. For example:

![In code editor](https://user-images.githubusercontent.com/18090165/219365729-ab8470f6-f4e0-4777-86d7-f7474ab88552.png)

![In the result](https://user-images.githubusercontent.com/18090165/219365771-7e9d40dc-e5a4-4386-b00c-6179c0c4d624.png)

Is this bug or feature? Maybe there is some way to escape?

**Comment by geoffreymcgill** [comment]
Hi @AlexKatyukov. The following post provides several options for configuring this scenario, see
https://github.com/retypeapp/retype/issues/426#issuecomment-1273342318

The `{{ field1 }}` token is getting parsed by the template engine. As easy work-around is to escape the code block, or turn off the Templating engine for the Page or for the entire Project. 

The following sample demonstrates how to escape the code block:

~~~
{%{
```twig
{{ field1 }}
```
}%}
~~~

Hope this helps.
