### ISSUE TITLE
Remove Default Welcome Page

### ISSUE THREAD

**Issue by micartey** [retypeapp/retype#535]
I am missing a feature to modify or overwrite the default welcome page and I couldn't find any information about that in your docs. I tried creating another Welcome Page but now I am left with this:

![image](https://user-images.githubusercontent.com/51415855/236684238-db97413b-e527-4e13-8a55-2d064838d846.png)

**Comment by geoffreymcgill** [comment]
Hi. Adding an `index.md`, `readme.md`, or `default.md` file to your project will override the default **Welcome** page that is generated. 

We have improved the experience in the upcoming Retype v3.0 release, so this should not be a problem in the future. 

Hope this helps.

**Comment by micartey** [comment]
Yes, thanks a lot!
Did I miss that somewhere? 🤔

**Comment by micartey** [comment]
I guess I did: https://retype.com/configuration/reserved_words/
Not sure if there are further notices on that topic

**Comment by geoffreymcgill** [comment]
We need to make it more obvious in the docs.

again, with the next release, it will be very clear too. 

We also added `welcome.md` as an option.
