### ISSUE TITLE
Unable to overwrite branch

### ISSUE THREAD

**Issue by micartey** [retypeapp/retype#536]
I am using the `retype-actions.yml` workflow provided on the website.
This works well for one project which is publicly available, but for the second project which is private, I cannot overwrite the branch. It works the first time. However, or when I delete the branch.

This is the workflow output:

```
Retype built documentation path: /tmp/tmp.86P4c6mGM7
Target branch: retype
Target directory: ./
Fetching remote for existing branches: done.
Branch 'retype' already exists.
fatal: 'retype' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
Switching to the 'retype' branch: error.
Error: unable to checkout the 'retype' branch.
Error: Process completed with exit code 1.
```

**Comment by geoffreymcgill** [comment]
HI @micartey. Can you share a copy of the `retype-actions.yml` file from your private project? Just so we're working with the exact same code. I will try the same setup and try to reproduce the same error.

**Comment by micartey** [comment]
It is the same as on the website. I just replaced `main` with `master`

```yml
name: Publish Retype powered website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest
        with:
          license: ${{ secrets.RETYPE_SECRET }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
```

**Comment by geoffreymcgill** [comment]
I tried to reproduce using a private repo and everything seems to be working fine. I don't think this error is related to being a private repo. There's something else about the repo that is failing in your case. 

Here are the log messages from my test repo at the same steps in the build action:

```
Retype built documentation path: /tmp/tmp.wCnvEouzwn
Target branch: retype
Target directory: ./
Fetching remote for existing branches: done.
Branch 'retype' already exists.
Switching to the 'retype' branch: done.
Cleaning up branch: found config.js's ID, done.
Deploying files: done.
Staging deployed files for commit: done.
Checking for changes in repository: changes found.
Committing files: done.
Pushing 'retype' branch back to GitHub: done.
Retype GitHub Action finished successfully.
```

It's going to be tough for me to diagnose the issue without being able to reproduce.

1. Switch the repo to `public` and send me (hello@retype.com) a link to the repo, OR
2. Send me (hello@retype.com) a .zip of the files for the project, OR
<img width="409" alt="Screen Shot 2023-05-08 at 9 19 15 PM" src="https://user-images.githubusercontent.com/62210/236985640-0e85f539-71b3-4e53-ac73-56cd8350d19a.png">
3. Set me (@geoffreymcgill) as a collaborator on the private repo

Any one of those should be enough.

Feel free to remove all of the `.md` content files, folders, and static files such as Images. I don't think the .md file are related to this issue.

**Comment by geoffreymcgill** [comment]
I don't think the following will solve the issue, but it's something easy to try.

Remove the `.github/workflows/retype-action.yml` file and turn off the GitHub Pages, then add back:

### Remove configuration

1. Remove the `.github/workflows/retype-action.yml` file and commit that change
2. Set the GitHub Pages branch to `none` and click the **Save** button
<img width="556" alt="Screen Shot 2023-05-08 at 9 28 56 PM" src="https://user-images.githubusercontent.com/62210/236986786-ab7a0c46-c754-4899-9a0e-d999349a309e.png">

### Add configuration

Now just add both back to you repo.

1. Add the `.github/workflows/retype-action.yml` file and commit that change
2. Set the GitHub Pages branch to `retype` and click the **Save** button

**Comment by micartey** [comment]
I found the issue.
I had a folder called `retype` at the root level of my project and had my documentation there.

Turns out that the script doesn't like it. To be more precise, when the branch `retype` already exists.
Renaming `retype` to sth else like `documentation` fixed the issue.

I will still let this issue open to refer to on a possible merge on `retypeapp/action-github-pages@latest`

**Comment by micartey** [comment]
Bump @geoffreymcgill

**Comment by geoffreymcgill** [comment]
Thanks for the update. We will try and reproduce the error.

For now, looks like renaming that folder is a temp work-around.

**Comment by geoffreymcgill** [comment]
I was able to reproduce the `fatal: 'retype' could be both a local file and a tracking branch.` error. We are investigating and will keep this thread up to date with our progress.

https://github.com/retypeapp/sampleproject/actions/runs/4962914129/jobs/8881560562#step:10:24

The test project is available at https://github.com/retypeapp/sampleproject/.

**Comment by geoffreymcgill** [comment]
This issue has been fixed. 

There are no changes required in your project. On the next change to your project, the new build action will be automatically applied. 

Thanks for reporting!
