### ISSUE TITLE
Disable Filter sidebar

### ISSUE THREAD

**Issue by anotherduckling** [retypeapp/retype#538]
Please add an option to disable `Filter` sidebar. It's one of the least used thing. Adding an option to disable this will be helpful. 
![image](https://user-images.githubusercontent.com/57977673/237025173-07bf120f-6a4a-41c0-bb3a-064cbfd208ea.png)

**Comment by geoffreymcgill** [comment]
Thanks for the feature request. At the moment, there is no config to hide the Filter component, but it is a good idea and we will try and implement in a future release. 

I will keep this thread updated with our progress.

**Comment by sergioSHKLR** [comment]
Second it.

**Comment by geoffreymcgill** [comment]
We might not implement a project config for this feature, but once #639 is implemented, hiding the tree nav filter should be simple. 

I'm going to close this issue but will post an update once #639 is available.

**Comment by sergioSHKLR** [comment]
Thank you very much for the prompt reply and accompanying info!

I'm trying to implement a custom layout based on the central one. It'd be a
responsive two column layout with an iframe so links from the first column
open in the second one. It'd be visible on large and medium breakpoints and
hidden on small.

I'm not a trained programmer, just an hobbyist so all my skills are self
taught. Once I figure out the templating language, I'll pony up for the Pro
license.

Thank you and your team for one of the cleanest looking SSG out there!


Sergio SHKLR, ETC(EXW)
🇺🇸 ⚓ US Navy, Ret. 1997-2018
🇮🇶 🎖️🎖️ 🇦🇫 🎖️🎖️ Veteran

**Comment by geoffreymcgill** [comment]
We have implemented hiding the sidebar filter as a Project setting. The new `showSidebarFilter` setting will be available in the next public release of Retype, which will be soon. 

```yml
showSidebarFilter: false # Default is true
```

Hope this helps.
