### ISSUE TITLE
Contents Sidebar goes to bottom

### ISSUE THREAD

**Issue by stefanlaux** [retypeapp/retype#543]
The Contents in the right Sidebar just go to the bottom

![image](https://github.com/retypeapp/retype/assets/90751877/f3d59f83-e313-40d7-92d8-600f9a9d4f04)

**Comment by geoffreymcgill** [comment]
Thanks for the report. This is the first time I've seen this happen. 

Can you provide any details on how to reproduce this issue?

**Comment by stefanlaux** [comment]
Yes, sure

when I start it the first time it looks like this:

![image](https://github.com/retypeapp/retype/assets/90751877/02097204-18e8-4861-840b-7b260d666ca1)

but then when I navigate to this tab:
![image](https://github.com/retypeapp/retype/assets/90751877/0f83ba22-5d06-41ce-931a-51fee237dac5)

the right sidebar goes to the bottom


But all the pages work except this one. And when i was on the "Mitarbeiter" tab and the right sidebar content goes to bottom and I navigate to another tab it stays on bottom but when i reload everything is normal except when i go back to the Mitarbeiter tab.

here is the code of this tab:

```
---
order: 95
icon: person
---
# Mitarbeiter

Die Mitarbeiter Funktion beinhaltet eine Liste aller Mitarbeiter, eine Lernenden-Übersicht für den Lehrmeister und Berufsbildner.
!!!
Man kann auf einzelne Mitarbeiter mit einem Doppelklick näher anschauen.
!!!

----

## Mitarbeiter Liste

Die Mitarbeiter Liste beinhaltet alle Mitarbeiter, die sich bei Admigo eingeloggt haben. Sie ist sichtbar für jeden Benutzer.

In dieser Liste kann man auf jeden Mitarbeiter einen Doppelklick machen, um alle Informationen übersichtlicher zu bekommen.
Lehrmeister und Berufsbildner können dort auch Informationen ändern oder Erinnerungsmails versenden.

### Rechte

| Lernender           | Berufsbildner       | Lehrmeister         | Beschreibung                             |
|---------------------|---------------------|---------------------|------------------------------------------|
| :icon-check-circle: | :icon-check-circle: | :icon-check-circle: | Informationen von Mitarbeitern anschauen |
| :icon-blocked:      | :icon-blocked:      | :icon-check-circle: | Informationen von Mitarbeitern verändern |
| :icon-blocked:      | :icon-check-circle: | :icon-blocked:      | Erinnerungsmails versenden               |


----------

## Zusätzliche Fenster
+++ Lernender
!!!
Der Lernende hat nur Zugriff auf die Mitarbeiter Liste
!!!

+++ Berufsbildner
## Lernende Liste
Der Berufsbildner hat zusätzlich noch Zugriff auf die Lernenden Liste, in welcher er nur seine Lernenden sieht.
So haben die Berufsbildner einen besseren Überblick wer alles Lernender von Ihnen ist.

Falls ein Lernender vergessen hat seinen Berufsbildner im Admigo zu ändern, kann er einen Doppelklick auf diesen Lernenden machen und
beim Berufsbildner Tab auf `Notify to change Berufsbildner` drücken. Danach wird der Lernende aufgefordert seinen Berufsbildner zu wechseln.

+++ Lehrmeister
## Meine Lernenden
Der Lehrmeister hat in diesem Fenster einen Überblick über die Lernenden und ihre üK Noten, sowie die Ausbildungsberichte die sie abgegeben wurden.
Ausserdem kann er alle üK anschauen, die je von den Lernenden absolviert wurden und sieht den Durchschnitt ihrer Resulate.

## Mitarbeiter hinzufügen
Der Berufsbildner hat zusätzlich noch Zugriff auf die Lernenden Liste, in welcher er nur seine Lernenden sieht.


```

**Comment by stefanlaux** [comment]
I found the Element that produces this bug:

![image](https://github.com/retypeapp/retype/assets/90751877/b7b426f3-6af0-4541-adee-9fbd68699f31)


is there any way to remove this bar?


<details><summary>Element</summary>
<p>
HTML:

```html
<div class="simplebar-track simplebar-vertical" style="visibility: hidden;">
    <div class="simplebar-scrollbar" style="height: 0px; display: none;">
    </div>
</div>
``` 
<div class="simplebar-track simplebar-vertical" style="visibility: hidden;">
    <div class="simplebar-scrollbar" style="height: 0px; display: none;">
    </div>
</div>


CSS:


![image](https://github.com/retypeapp/retype/assets/90751877/ffeb9e2a-0005-4742-b3b2-be25bd40cae3)



</p>
</details>

**Comment by geoffreymcgill** [comment]
There is not a way to remove those elements or the simplebar library. While simplebar might be involved in this issue, the first step would be for us to reproduce the issue and investigate what is causing the problem. At the moment, we cannot reproduce, so we do not have any suggestions on how to fix or work-around.

**Comment by stefanlaux** [comment]
I fixed it by deleting the retype project and then reinstall everything and add the content
perhaps it was my fault somewhere.

@geoffreymcgill thanks for making this project it is very helpful

**Comment by geoffreymcgill** [comment]
Thanks for the update. If you happen to trigger the issue again, please let us know how to reproduce and we will investigate.
