### ISSUE TITLE
Restore the old ghost badge style

### ISSUE THREAD

**Issue by anotherduckling** [retypeapp/retype#552]
The current text in badge style looks almost like dark badge. Please bring back the old style. It looks too bright. Older version was useful if I had to add too many tags. Now it kinda looks overwhelming. 

![image](https://github.com/retypeapp/retype/assets/57977673/71196137-27cf-45a5-9ad1-4774b67fe7a6)

**Comment by anotherduckling** [comment]
Also, is the font changed in pre 3.0.0?

**Comment by geoffreymcgill** [comment]
Hi. Which version of Retype are you currently using? please check using `retype --version` 

Also, can you post a sample of the Badge component config you are using here?

The badge colours should not have changed, so this might be a defect.

**Comment by geoffreymcgill** [comment]
> Also, is the font changed in pre 3.0.0?

Yes.

**Comment by anotherduckling** [comment]
> Which version of Retype are you currently using?

I am trying the pre 3.0.0 
https://github.com/anotherduckling/Wotaku/blob/main/.github/workflows/retype-action.yml

**Comment by anotherduckling** [comment]
> > Also, is the font changed in pre 3.0.0?
> 
> Yes.

Is it possible to add an option to use the old font. The current font for the Brand name looks kinda weird/odd.

![image](https://github.com/retypeapp/retype/assets/57977673/a130cbb2-42df-4a39-a315-482fcaa49bd6)

Maybe I was getting used to the old font.

**Comment by anotherduckling** [comment]
> The badge colours should not have changed, so this might be a defect.

![image](https://github.com/retypeapp/retype/assets/57977673/bb7c172c-4745-41c6-909d-8a0f5334b26d)

the old ghost button was like this one.

**Comment by anotherduckling** [comment]
`- [CDJapan](https://www.cdjapan.co.jp/) [!badge variant="ghost" size="xs" text="Manga"] [!badge variant="ghost" size="xs" text="Anime"] [!badge variant="ghost" size="xs" text="OST"] [!badge variant="ghost" size="xs" text="LN"]  [!badge variant="ghost" size="xs" text="Merch"] [!badge variant="ghost" size="xs" text="Physical"]`

**Comment by geoffreymcgill** [comment]
I was able to reproduce. This is a defect and I will try to fix right away, in time for the final `v3.0.0` release. 

Thanks for reporting.

**Comment by geoffreymcgill** [comment]
This defect has been fixed and the fix will be included in the upcoming v3.0.0 final release. 

Here's your badge sample using the latest v3.0 style:

<img width="176" alt="Screen Shot 2023-05-27 at 12 00 08 PM" src="https://github.com/retypeapp/retype/assets/62210/ec10174b-24b8-48db-89d8-6b32ac2c1a89">

Hope this helps. Thanks for reporting the defect.
