### ISSUE TITLE
Using the Blog Summary Page as Home Page?

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#553]
I'm currently exploring using Retype for a Final Cut Pro news site: https://fcp.cafe

I was just wondering if it's possible to make the home page the Blog Summary page?

I would still like the home page to have the left navigation panel.

Ideally, I'd also love to be able to customise the top of the blog summary page, and change the title (i.e. "Latest News" instead of "Blog").

Is this currently possible, or will I need to throw together some GitHub actions to make it work?

Thanks team! I LOVE your product, and use it for EVERYTHING.

**Comment by geoffreymcgill** [comment]
> I was just wondering if it's possible to make the home page the Blog Summary page?

Currently, Retype does not have the ability to assign the Blog summary page as the home page of the website. Although, this is a feature we have talked about and would like to include in a future release. For now, the Blog functionality is limited. 

> I would still like the home page to have the left navigation panel.

One option that might work for you is creating a page with [`redirect`](https://retype.com/configuration/page/#redirect) to the /blog page. Not ideal, but it's something you could experiment with.

A basic page with a redirect would be the following:

```md
---
label: News
redirect: /blog
---
```

> Ideally, I'd also love to be able to customise the top of the blog summary page, and change the title (i.e. "Latest News" instead of "Blog").

Add an `index.md` or `default.md` or `readme.md` into your `/blog/` folder and whatever you place in that page will be rendered above the Blog summary cards.

In Retype v3.0, you can use `blog.md` as well, but I don't think that is supported in v2.4. 

> Thanks team! I LOVE your product, and use it for EVERYTHING.

Awesome! Thanks so much for the feedback and for using Retype.

**Comment by geoffreymcgill** [comment]
Your fcp.cafe project looks excellent. Really nice use of Retype. Good job. 

How are you doing the YouTube embeds? using the [embed](https://retype.com/components/embed/) component?

I have some plans to make embedding YouTube (and many others) widgets much easier and cleaner. I'm not sure when we'll get this built, but it's high on my list of priorities.

**Comment by geoffreymcgill** [comment]
ah, I see, you're using the [Container](https://retype.com/components/container/) component. Interesting.

```
:::videocontainer
<iframe class="video" src="https://www.youtube-nocookie.com/embed/oT68XsbEvmE?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
:::
```

**Comment by geoffreymcgill** [comment]
I'm sure you are aware, but just in case you are not, you can combine the `.yml` and `.md` into one file. Then everything to do with the page is encapsulated into a single file.

Your [podcasts.md](https://github.com/CommandPost/FCPCafe/blob/main/docs/podcasts.md) would be combined into the following:

**NOTE**: Actually, you wouldn't require the `label` config either.

```md
---
icon: broadcast
order: 537
---
# Podcasts

...
```

But, keeping them separate is definitely nice too, if you want to cleanly separate the content from the config.

Hope this helps.

**Comment by geoffreymcgill** [comment]
Sorry, I noticed one more thing. Looks like your project needs a `favicon`. Just add a `favicon.ico` or `favicon.png` file into the root of your project, or set [`favicon`](https://retype.com/configuration/project/#favicon) project config if you want to keep the favicon file elsewhere.

Hope this helps.

**Comment by latenitefilms** [comment]
Thanks for the detailed comments and replies @geoffreymcgill - HUGELY appreciated!

> Your fcp.cafe project looks excellent. Really nice use of Retype. Good job.

Thank you!! It's very much a work-in-progress, but so far it's been fun!

FWIW - I use your amazing project for EVERYTHING!

[fcp.cafe](https://fcp.cafe)
[brawtoolbox.io](https://brawtoolbox.io)
[markertoolbox.io](https://markertoolbox.io)
[recalltoolbox.io](https://recalltoolbox.io)
[transfertoolbox.io](https://transfertoolbox.io)
[gyroflowtoolbox.io](https://gyroflowtoolbox.io)

...and I'm planning to move [commandpost.io](https://commandpost.io)'s documentation away from GitBooks to Retype as well.

Regarding [fcp.cafe](https://fcp.cafe) I think what I'll try do is just create a GitHub action that automatically generates a new RSS feed when I update the README. This is probably the easiest/cleanest solution for now.

To be honest, I didn't even know about the `embed` feature - but I don't think I'd use it anyway, as I want to use YouTube's "privacy-enhanced mode".

> I'm sure you are aware, but just in case you are not, you can combine the `.yml` and `.md` into one file. Then everything to do with the page is encapsulated into a single file.

Yes, I'm aware of this - I figured it was nicer/cleaner to keep them seperate.

> Sorry, I noticed one more thing. Looks like your project needs a favicon

Yes, thanks for the reminder! The current FCP Cafe icon was just generated by Midjourney, and is a bit funky, so I'm hoping to replace with a human-generated icon at some point, and we'll add a favicon then as well.

Again, thanks so much for your detailed reply, and such a great project!

Whilst I've got you... and this is asked for is another issue I think is that it would be great if you added an option to disable the header icon/image on mobile. For example, look at [markertoolbox.io](https://markertoolbox.io) on a phone. I'd prefer the text to be visible, instead of prioritising the icon/image.

**Comment by latenitefilms** [comment]
For anyone who stumbles across this site, after a bit of back and forth with good olde ChatGPT, I managed to write a GitHub Action for automatically generating a new `rss.xml` file, based off my `README.md`.

For anyone who's interested, you can find the code here:

https://github.com/CommandPost/FCPCafe/blob/main/.github/workflows/retype-action.yml

I'm going to close this issue for now. Thanks team!

**Comment by geoffreymcgill** [comment]
Something that could be fun to get working is moving each of those News items into a separate include file, then running a script add the latest news items to the home page.

Each new items would be created as a separate `.md` file. Naming the file with a ISO 8601 date standard would make them easily sortable and easily parsable. 

<img width="408" alt="Screen Shot 2023-05-29 at 12 16 54 PM" src="https://github.com/retypeapp/retype/assets/62210/776827af-2504-4c72-a638-18df274e8b53">

Then your script would loop through those `_includes/news/*.md` files and write the `{{ include }}` statement into your News summary page (**readme.md**). It would look something like the following if you were manually building the summary page.

```md
# Latest News

{{ include "news/2023-05-29.md" }}

---

{{ include "news/2023-05-28.md" }}

---

{{ include "news/2023-05-27.md" }}

---
```

The script could automatically add the `---` separator as it's looping through the news items. 

That might also make creating the `.rss` feed easier, as you wouldn't have to directly parse the **readme.md**. Of course you already have that working, so no savings there, but maybe a little cleaner process.

Hope this helps.

**Comment by geoffreymcgill** [comment]
hmmm. An even cleaner technique would be having the script combine into a **_includes/news/summary.md** file, then just include that file into the **readme.md**. Then you wouldn't even need to touch the **readme.md**. Super clean. 

#### readme.md

```md
# Latest News

{{ include "news/summary" }}
```

#### summary.md

```md
{{ include "2023-05-29" }}

---

{{ include "2023-05-28" }}

---

{{ include "2023-05-27" }}

---
```

Hope this helps.

**Comment by latenitefilms** [comment]
Great ideas! Thank you!

**Comment by latenitefilms** [comment]
@geoffreymcgill - Unrelated, but whilst I've got you... is there an easy way to hide an image when in mobile view? I want to hide the logo on the home page when on mobile so it doesn't go behind the section list icon. Thoughts?

https://fcp.cafe

**Comment by geoffreymcgill** [comment]
> is there an easy way to hide an image when in mobile view?

Off the top of my head, I don't know of solution, but I will look into it. 

When you get a chance, create a new Issue for this question.
