### ISSUE TITLE
Page with header + title

### ISSUE THREAD

**Issue by rab-dev** [retypeapp/retype#559]
Hi,

I think I've found an inconsistency between the displaying of pages titles (explicit v implicit) when including a header image on a page. As always could be my limited understanding but I have checked and it seems legit.

Hope this helps.

---

## Problem

Case #1 : Page with Header:

```
![](https://retype.com/static/retype-hero.png)

# Page with header

This is a page with a top feature image as the header.
```

This displays the image at the top of the page with the page title below the image.

---

Case #2 : Page with Header + Title:

```
---
title: Hello Title
---
![](https://retype.com/static/retype-hero.png)

# Page with header + title

This is a page with a top feature image as the header and a title.
```

This displays the page title (Hello Title) at the top of the page with the image below the title.

![Capture](https://github.com/retypeapp/retype/assets/61521617/b471b8cc-0339-40ad-b854-e1654b27d293)

## Proposal

In Case #2 the new title (Hello Title) should not be displayed.

---

**Comment by rab-dev** [comment]
Thanks.

This has come up when writing my docs. I'm happy of course to be told it's not the right way and to learn the correct way.

Use case is:

1. I have a long title on a page "How My Amazing Awesome Thing Works".
2. The title is too long to be displayed in the index in the lhs side panel (looks awkward).
3. I set the `title` config to "How it Works".

This works as intended. Short index title. Long page title.

I add a page header (image) and it breaks as both titles are then shown on the page.

My workaround is simply not to add the page header (image).

So it's not urgent & not a deal breaker, but thought it useful to report.

**Comment by geoffreymcgill** [comment]
@rab-dev Thanks for the additional details. 

> 2\. The title is too long to be displayed in the index in the lhs side panel (looks awkward).

You can use the `label` config to set a custom value for the left tree navigation node. 

```yml
---
label: How it Works
---
# How My Amazing Awesome Thing Works
```

Using the `label` will also work correctly if using a header image.

We should be able to still support your original proposal, but looks like setting the `label` config is what you need for your scenario.

Hope this helps.

**Comment by rab-dev** [comment]
Perfect. 

`label` is the correct call, works with the header image and gives me what I wanted.

Thank you. My bad. Apologies.
