### ISSUE TITLE
Tab collapsed by default?

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#560]
Is there a way to make a tab collapsed by default?

For example, I'm using it to show different information for different browsers on my home page, but I'd prefer the Safari content to be hidden until you click the link?

<img width="1115" alt="image" src="https://github.com/retypeapp/retype/assets/22286696/ae02d370-a37f-49f4-9e9f-9e86e115328c">

**Comment by geoffreymcgill** [comment]
Not supported, but how about wrapping the Tab panel in a collapsible Panel? 

```md
==- :icon-bookmark: Make FCP Cafe your Home Page
+++ Safari
1. Step 1
2. Step 2
3. Step 3
+++ Chrome
+++ Firefox
+++ Microsoft Edge
+++ Internet Explorer
+++
===
```

<img width="889" alt="Screen Shot 2023-05-30 at 4 33 40 PM" src="https://github.com/retypeapp/retype/assets/62210/67b3c261-1161-4670-ab92-d52a5bd64f89">

Then expanded, the Panel would look like:

<img width="893" alt="Screen Shot 2023-05-30 at 4 33 46 PM" src="https://github.com/retypeapp/retype/assets/62210/4d37b3ab-2fdc-451e-8641-e552b83e0590">

**Comment by geoffreymcgill** [comment]
Another option could be stacked collapsed Panels. 

```md
==- Safari
1. Step 1
2. Step 2
3. Step 3
==- Chrome
==- Firefox
==- Microsoft Edge
==- Internet Explorer
===
```

<img width="901" alt="Screen Shot 2023-05-30 at 4 36 11 PM" src="https://github.com/retypeapp/retype/assets/62210/f9d2009f-fcb3-4cf2-8427-7c14028f70f0">

Then expanded, the Panels would look like:

<img width="899" alt="Screen Shot 2023-05-30 at 4 36 20 PM" src="https://github.com/retypeapp/retype/assets/62210/6bdd9f96-cf35-4b9e-845b-81390663df76">

Hope this helps.

**Comment by latenitefilms** [comment]
Genius! Thank you!
