### ISSUE TITLE
Cache Clarification?

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#563]
I just noticed this in my websites code:

```
<meta name="turbo-cache-control" content="no-cache" data-turbo-track="reload" data-track-token="3.0.1.738976285563">
```

What does it actually do?

One thing I've noticed when testing my site with [GTmetrix](https://gtmetrix.com) is that it suggests "Serve static assets with an efficient cache policy". Is this something I can tweak with Retype?

<img width="1041" alt="image" src="https://github.com/retypeapp/retype/assets/22286696/49633379-5d60-459f-bb42-998c4ade00bd">

Also, whilst I've got you... it would be amazing if something could be added to the documentation under hosting to explain the pro's and con's between GitHub Pages vs Docker vs Cloudflare vs Netlify.

Would there be big performance improvements moving from GitHub Pages to Cloudflare, for example?

**Comment by geoffreymcgill** [comment]
> One thing I've noticed when testing my site with [GTmetrix](https://gtmetrix.com) is that it suggests "Serve static assets with an efficient cache policy". Is this something I can tweak with Retype?

Unfortunately, this is a web server setting and not something that Retype can adjust in the static files. 

The short expiry cache policy is an issue with GitHub Pages where they set files to expire in 10 minutes by default by setting the `CacheControl: max-age=600` header (600 seconds). Others have run into the same issue with GitHub Pages, see

https://webapps.stackexchange.com/questions/119286/caching-assets-in-website-served-from-github-pages
https://github.com/orgs/community/discussions/11884

This is also exactly the reason why we just moved retype.com from GitHub. Currently, the site is hosted on Netlify, although I see `cache-control: public, max-age=0, must-revalidate` in the response headers, so I'm not sure what's up with that. The current GTmetrix score is better now though: https://gtmetrix.com/reports/retype.com/DTqqXoLW/.

<img width="620" alt="Screen Shot 2023-06-02 at 12 13 41 PM" src="https://github.com/retypeapp/retype/assets/62210/b351d50d-a063-4b16-9a61-aecb1eee096a">

I think I also enabled the **Proxied** status on the Cloudflare DNS config, so they might be fidgeting with the cache headers now.

GitHub Pages, Netlify, and Cloudflare Pages are all excellent and essentially provide the same. They all require very minimal setup and automatically push updates to your website when your update your GitHub project, if you're using the Retype GitHub [Build Action](https://retype.com/guides/github-actions/).

I suspect you would not actually notice much of a performance difference if moving from one service to another, but those performance report services like GTmetrix do report better scores if using Netlify or Cloudflare Pages. My guess is Cloudflare Pages will give the best performance, but that is just a guess. 

Writing up a deep dive comparison into hosting options is a good idea and I'll try to put a document together.

Hope this helps.

**Comment by latenitefilms** [comment]
I just tried turning on the free CloudFlare service for https://fcp.cafe, to see if that makes any difference.

**BEFORE:**

![image](https://github.com/retypeapp/retype/assets/22286696/52491bd3-8a5e-4253-87f9-e6308915f13c)

**AFTER:*

<img width="1333" alt="image" src="https://github.com/retypeapp/retype/assets/22286696/5d334159-eeeb-4ba5-ae68-d873e4dc0411">

...so, not really much of a difference, at least not in that specific test.

From an end-user perspective though, site feels very fast.

Thanks again for the detailed reply!

**Comment by geoffreymcgill** [comment]
If you are GitHub Pages and Cloudflare for your DNS, the following setting might help:

<img width="855" alt="Screen Shot 2023-06-02 at 1 40 55 PM" src="https://github.com/retypeapp/retype/assets/62210/1d36d9a2-2f51-4502-a5ac-d8209f03b769">

**Comment by latenitefilms** [comment]
You're an absolute legend @geoffreymcgill  - thank you! You're awesome.

<img width="1323" alt="image" src="https://github.com/retypeapp/retype/assets/22286696/ded76c1e-7a72-4c0f-88cd-fd706c2aa4a9">

<img width="1056" alt="image" src="https://github.com/retypeapp/retype/assets/22286696/bb3eb7d9-c248-4f9c-a571-b357d8927759">
