### ISSUE TITLE
CSS Sidebar Customization Class

### ISSUE THREAD

**Issue by Nzii3** [retypeapp/retype#567]
What class would I need to customize in `custom.css` to change the color of this text?
![image](https://github.com/retypeapp/retype/assets/106406461/ff84f5c5-06fb-4af9-a8d0-e7c9d32e0ee5)

**Comment by geoffreymcgill** [comment]
Best I can suggest is to inspect the CSS using the browser developer tools and try to override the related class(es) in your **custom.css** file.

Currently, there are no configs within Retype to change the font color or theme. We do hope to support custom theming in a future release, but for now, there are no options within Retype.
