### ISSUE TITLE
Dark Mode support for giscus on Retype?

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#568]
Following on from #564, I'm having trouble getting dark mode to play nicely with giscus on Retype.

Any tips or tricks?

**Comment by geoffreymcgill** [comment]
For me, Giscus automatically switched to their dark theme when the system appearance changed from day (light) into evening (dark). 

The Giscus theme will be completely independent/separate from the Retype theme.

**Comment by geoffreymcgill** [comment]
If you're on a Mac, you can switch the Appearance between **Light** and **Dark** to see the Giscus widget theme updating.

<img width="370" alt="Screen Shot 2023-06-07 at 3 58 26 PM" src="https://github.com/retypeapp/retype/assets/62210/47e6cc9b-3ab7-48bf-bb54-10d7b5222af5">

**Comment by latenitefilms** [comment]
I expect it to switch when you change the light/dark mode via this button - but it doesn't seem to? 

<img width="46" alt="image" src="https://github.com/retypeapp/retype/assets/22286696/9ffc45ee-68e5-41fa-a050-1ef2f0f7f47e">

**Comment by geoffreymcgill** [comment]
> I expect it to switch when you change the light/dark mode via this button - but it doesn't seem to?

Sorry, but the Giscus widget is 100% separate from Retype. Giscus is rendered in an `<iframe>` is essentially a completely different web site, disconnected from your Retype generated website. The Giscus widget would not be listening for the Theme switching on its parent (retype app).

Theoretically, if Giscus had a [Parent-to-giscus](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#parent-to-giscus-message-events) event that allowed for switching the Giscus theme, then it would be possible to listen for the `dark` mode change on the Retype side and call Giscus to switch the theme. To the best of my knowledge, that event or API hook is not available on Giscus. 

There might be security issues as well with the Parent (retype app) document calling into the Child (Giscus iframe) document.  In general, `<iframe>` documents are pretty locked down in most modern browsers as `<iframe>`'s open up a security risk.

**Comment by latenitefilms** [comment]
Understood. Thanks for the detailed reply!
