### ISSUE TITLE
Collapsed Panel shows full panel during initial page load?

### ISSUE THREAD

**Issue by latenitefilms** [retypeapp/retype#570]
This is soooooo minor, but I still find it annoying, so I wonder if there's an easy CSS fix?

We have the following markdown for our home page:

```
==- :icon-bookmark: Make FCP Cafe your Home Page
+++ Safari
1. In the top left corner of your screen, select **Safari** and then **Preferences** and then **General**.
2. Next to **New windows open with** and **New tabs open with**, select **Homepage**.
3. Next to **Homepage** enter: `https://fcp.cafe`.
+++ Chrome
1. In the top right corner of your computer's browser, click **More** icon and then **Settings**.
2. Under **Appearance**, turn on **Show home button**.
3. Select your current homepage, then, enter: `https://fcp.cafe`.
+++ Firefox
1. Drag this tab to the **Home** button, then release.
2. Click **Yes**.
+++ Microsoft Edge
1. In the upper right corner of your browser, select the **More** icon and then **Settings**.
2. Under **Set your homepage**, click the Down arrow and then **A specific page or pages**.
3. If you have a current homepage: Next to the URL, click **X**.
4. Click **Enter a URL**. Then, type: `https://fcp.cafe`.
+++ Internet Explorer
1. In the menu bar on the top of your browser, click **Tools**.
2. Select **Internet Options**.
3. Click the **General** tab.
4. Under "Home page," enter: `https://fcp.cafe`, click OK and restart your browser.
+++
===
```

When Safari first loads, it shows the full contents, then a second or so later it compressed down to a panel.

Is there anyway to make it "hidden" when loading?

You can see in action here: https://fcp.cafe

**Comment by geoffreymcgill** [comment]
I have noticed this as well and find it annoying too. I will investigate and see if we can find a way to work around.

**Comment by latenitefilms** [comment]
@geoffreymcgill - This is actually starting to annoy me a lot more, as my home page gets bigger/more complex and the page takes longer to load:

https://fcp.cafe

I'm assuming you could just hide the collapsed panel by default using in-line CSS as a workaround?

**Comment by geoffreymcgill** [comment]
> This is actually starting to annoy me a lot more,

Confirmed, annoying. I look into this today.

**Comment by geoffreymcgill** [comment]
The rendering of the Tab content has been improved and now the content will be hidden until the Tabs are finished rendering. This will avoid the flash of unstyled content before the Tabs have fully rendered.

The enhancement will be included in the upcoming Retype v3.1 release.

@latenitefilms Thanks for reporting the issue and for the gentle reminder.

Hope this helps.

**Comment by latenitefilms** [comment]
Legend, thanks SO MUCH! HUGELY appreciate you fixing what's really just a non-issue glitch.

Can't wait to test out the new version!

**Comment by geoffreymcgill** [comment]
> Can't wait to test out the new version!

Retype v3.1 should be released on (or before) Monday.
