### ISSUE TITLE
Obscuring Analytics Path

### ISSUE THREAD

**Issue by anotherduckling** [retypeapp/retype#575]
Is it possible to implement something like [Next-Plausible](https://github.com/4lejandrito/next-plausible) in Retype? A good chunk of my site users use Ad Blocker, which affects the analytics. I don't have any prior knowledge in coding, so don't really know is it possible to add this in retype.

**Comment by geoffreymcgill** [comment]
Plausible is supported by Retype, see https://retype.com/configuration/project/#plausible. 

Another option is to use the `_includes/head.html` file to include any custom `<script>`, see https://github.com/retypeapp/retype/discussions/282#discussioncomment-2343005.

Hope this helps.
