### ISSUE TITLE
Style being overwritten

### ISSUE THREAD

**Issue by micartey** [retypeapp/retype#577]
I have an image which should take the whole width

```css
img {
    width: 100%;
}
```

This works locally. However, once pushed it will just be ignored

**Comment by micartey** [comment]
Using the `img` html tag and changing the width does even worse.
The image just vanishes.

**Comment by geoffreymcgill** [comment]
If you are just trying to style one or a few images, then using a custom attribute would be better. For example:

```md
![](/static/sample.jpg){ style="width: 100%" }
```

Hope this helps.

**Comment by micartey** [comment]
Thank you, this helps a lot !
