### ISSUE TITLE
WARNING: Sidebar item 'retype' was not found.

### ISSUE THREAD

**Issue by altworkz** [retypeapp/retype#579]
What is the possible cause of this warning?

**Comment by geoffreymcgill** [comment]
There is something about the left sidebar tree navigation creation that the app is finding a conflict with. Maybe a folder or a navigation node named `retype`?

Any chance you could narrow down the issue into a reproducible sample? Or, is your project available on GitHub?

**Comment by altworkz** [comment]
That's it! There's an unnecessary `retype` folder. The building proceeded without warnings this time. Thank you for your prompt response.
