### ISSUE TITLE
Add sitemap generator

### ISSUE THREAD

**Issue by slimooo** [retypeapp/retype#58]
Hello,

It's possible to generate automaticly a sitemap or a rss feed ?

Thank you

**Comment by geoffreymcgill** [comment]
Yes we can. We are 💯 going to build this functionality, although it will not make it into the upcoming `v1.8.0` release. Maybe `v1.9.0`. 

@slimooo The RSS feed for blog posts is an easy to support, but would you want an RSS for all other content pages?

Generating the `sitemap.xml` for the entire site will not be a problem.

**Comment by slimooo** [comment]
Thanks !

No sitemap is perfect. In Google search console you can choose sitemap or feed. For my usage is'nt mandatory.

Thanks again ! 👍

**Comment by geoffreymcgill** [comment]
Automatic generation of the `sitemap.xml` is now included in Retype `v1.8`.

Generation of the rss feed for /blog posts will be included in a future release.
