### ISSUE TITLE
Last edit timestamp

### ISSUE THREAD

**Issue by anotherduckling** [retypeapp/retype#605]
Can a functionality be integrated into Retype that displays the date of the last edit when I make changes to the markdown?

![image](https://github.com/retypeapp/retype/assets/57977673/83b79183-d99f-4b8b-aa35-26bc67ddbdbb)

On the right side maybe, since “Edit this page” is already on the left side.

**Comment by geoffreymcgill** [comment]
Closing as a duplicate. This feature request is being discussed in #383.
