### ISSUE TITLE
how customize the css

### ISSUE THREAD

**Issue by qwerewqwerew** [retypeapp/retype#610]
I want to customize the css.
in the rettype.yml file
theme:
override: './static/override.css
I wrote the and put the file in that path
It doesn't apply
Please let me know the link to the relevant guide

**Comment by geoffreymcgill** [comment]
Hello. You can add a reference to your custom .css file by using the `_includes/head.html` file. Additional details available at https://github.com/retypeapp/retype/discussions/282#discussioncomment-2343005

Hope this helps.
