### ISSUE TITLE
Header Image

### ISSUE THREAD

**Issue by sledgemasterrrr** [retypeapp/retype#611]
I am unable to make pages have a header image while having a custom logo. 
 
This is my test page 
---
icon: "/logo.png"
---
![](ebay.png)

This is a page with a top feature image as the header.

But when i download the page from [the demo page](https://retype.com/samples/page-with-header/#page-with-header) everything works fine.

Is it not possible to have a header image while also choosing a custom logo? I hope I am wrong.

**Comment by geoffreymcgill** [comment]
> Is it not possible to have a header image while also choosing a custom logo? 

Should not be a problem. The demo page you linked to has both a custom header image and custom site logo. Here is the source for that page:

https://github.com/retypeapp/retype/blob/main/samples/page-with-header.md

Hope this helps.

**Comment by sledgemasterrrr** [comment]
> > Is it not possible to have a header image while also choosing a custom logo?
> 
> Should not be a problem. The demo page you linked to has both a custom header image and custom site logo. Here is the source for that page:
> 
> https://github.com/retypeapp/retype/blob/main/samples/page-with-header.md
> 
> Hope this helps.

![image](https://github.com/retypeapp/retype/assets/95257207/6c7dd50d-1946-45f8-a41f-02d7c31444ce)
It dosent have a logo

**Comment by sledgemasterrrr** [comment]
![image](https://github.com/retypeapp/retype/assets/95257207/17308032-4527-4b0a-98de-970db15bbe06)
![image](https://github.com/retypeapp/retype/assets/95257207/b1999c48-1745-4ca6-8cad-517760163290)

**Comment by geoffreymcgill** [comment]
> It dosent have a logo

Okay, I see what you are referring to, the [`icon`](https://retype.com/configuration/page/#icon) config. 

I have added an icon to those pages.

**Comment by geoffreymcgill** [comment]
I tested the page using `icon: /logo.png` and it seems to work fine as well.
