### ISSUE TITLE
Surprising behavior from the Github Action

### ISSUE THREAD

**Issue by patricklafrance** [retypeapp/retype#615]
Hello!

We are experiencing a surprising behavior with the Official Retype Github Action that we use to deploy our website to Github Pages.

Our website is still on Retype `v3.2.0` as you can see [here on our main branch](https://github.com/gsoft-inc/wl-web-configs/blob/main/package.json#L44) but after we merged a PR (that is not upgrading Retype to `v3.3.0`) our [website now has a breadcrumb](https://gsoft-inc.github.io/wl-web-configs/browserslist/configure-project/).

I am therefore wondering if the Github Action automatically use the latest version of Retype even if the website project is not targeting Retype latest version?

We are using fix versioning:

```
    "devDependencies": {
        "retypeapp": "3.2.0"
    }
```

Thank you,

Patrick

**Comment by geoffreymcgill** [comment]
Retype does not read or otherwise use the `package.json` file.

In your `retype-action.yml` file, the Retype build is configured to use the `latest` release of Retype:

https://github.com/gsoft-inc/wl-web-configs/blob/main/.github/workflows/retype-action.yml#L19

```yml
- uses: retypeapp/action-build@latest
```

Hope this helps.

**Comment by patricklafrance** [comment]
Oh, I blindly copied the documentation hehe thank you.

Are you aware if there's a way to use the package.json version of `retypeapp` instead?

For security reason, we usually do not install automatically the latest version of a dependency.

**Comment by geoffreymcgill** [comment]
You can point to a specific version in the `retype-action.yml`:

```
- uses: retypeapp/action-build@v3.2
```

Even `@v3` would work, if you want to limit to minor version releases.

> Are you aware if there's a way to use the package.json version of retypeapp instead?

No, nothing built into Retype, but you could create a custom action that read the version from `package.json` and updated the `- uses: retypeapp/action-build@v<version-here>` in your `retype-action.yml`.

Hope this helps.

**Comment by patricklafrance** [comment]
Thanks for the help, appreciated. We will probably develop a custom action.
