### ISSUE TITLE
Add --strict parameter for "retype build"

### ISSUE THREAD

**Issue by ogenstad** [retypeapp/retype#618]
It would be good with some form of strict parameter that would return a non-zero exit code if the build had warnings in it.

**Comment by geoffreymcgill** [comment]
We will be adding a new `retype build --strict` flag to the next release of Retype.

**Comment by ogenstad** [comment]
Thanks! ❤️

**Comment by geoffreymcgill** [comment]
The new `--strict` flag has been added and will be included in the next release of Retype.

**Comment by ogenstad** [comment]
Do you by any chance have an ETA for version 3.6.0?

**Comment by geoffreymcgill** [comment]
> Do you by any chance have an ETA for version 3.6.0?

We're trying. 

BTW, the new `--strict` flag will be Retype Pro only. Just something to keep in mind. 

https://github.com/retypeapp/action-build#strict
