### ISSUE TITLE
Invalid token found `,`. Expecting <EOL>/end of line.

### ISSUE THREAD

**Issue by patricklafrance** [retypeapp/retype#622]
Hello!

Whenever my code block includes a React style attribute with a comma to separate style values, the Retype compiler display a warning:

`WARNING: [guides\add-authentication.md:208,51] Invalid token found `,`. Expecting <EOL>/end of line.`

![image](https://github.com/retypeapp/retype/assets/794579/7e8e0d2d-186e-4ea7-8fe4-f596c9526a97)

Maybe I am getting too tired, but it seems like valid React/TSX code to me:

```jsx
<div style={{ whiteSpace: "nowrap", marginRight: "20px" }}>
    ....
</div>
```

If I remove the comma, no warning:

```jsx
<div style={{ whiteSpace: "nowrap" }}>
    ....
</div>
```

The code block language is set to `tsx`.

Thank you,

Patrick

**Comment by geoffreymcgill** [comment]
The `{{ }}` double curly-braces is the default Retype templating syntax and that code is trying to be executed by the templating engine. 

There are several options to either disable the templating engine or escape those code samples. Please see the following comment:

https://github.com/retypeapp/retype/issues/426#issuecomment-1273342318

The following sample escapes the entire code block:

~~~
{%{
```
<div style={{ whiteSpace: "nowrap", marginRight: "20px" }}>
    ....
</div>
```
}%}
~~~

Hope this helps.

**Comment by patricklafrance** [comment]
Oh got it. Yes that helps, thank you!
