### ISSUE TITLE
Keep the same active color scheme when navigating through a hub sites

### ISSUE THREAD

**Issue by patricklafrance** [retypeapp/retype#624]
Hello!

With the new hub feature of Retype v3.4, would it be possible to keep the same active color scheme (theme) when navigating between the hub sites?

In the following example, my hub site currently has the light color scheme activated while both of my other sites has the dark color scheme activated:

![color_scheme](https://github.com/retypeapp/retype/assets/794579/bf37008d-75e7-43eb-8243-fe7842e051be)

Thank you,

Patrick

**Comment by geoffreymcgill** [comment]
If the different websites are all hosted under the same domain name, then I think we might be able to make this work.

Theoretically, if you have `companyx.github.com/project-a` and `companyx.github.com/project-b`, they can both read from the same web browser local storage.

I don't think this would be possible if the projects are hosted until different domain names or sub-domain names. For example, `example.com` and `sample.com` would not be able to share the theme. As well, `example.com` and `docs.example.com` _might_ not be able to share the theme, although we need to test and confirm.

I will keep this thread updated with our progress.

**Comment by patricklafrance** [comment]
Indeed, they would have to be hosted on the same domain, which, in my opinion makes sense for a hub.

**Comment by geoffreymcgill** [comment]
We also need to build a new `System` option into the theme selector. So `Dark`, `Light`, and `System`. Or, `Day`, `Night`, and `System`. The `System` option is currently the _default_ theme option, where the theme will update based on the users OS preferences, but there currently is not an option to switch back to the System (default) option once either Dark or Light has been selected. 

If the theme is tracking the System, then all deployments whether they are on the same domain or not will render with the same theme.

**Comment by patricklafrance** [comment]
While it make sense to add a `System` option, I wonder how often someone who choosed explicitly to go for a light or dark theme for a website wants to go back to `System` ?

**Comment by geoffreymcgill** [comment]
You can manually clear the `doc_theme` key using the browser developer tools:

<img width="696" alt="Screen Shot 2023-09-10 at 1 03 11 PM" src="https://github.com/retypeapp/retype/assets/62210/5b8e3d01-2b54-44cd-9b8d-c9f63e1dc3d3">

Once the new `System` option is in place, it will essentially delete the `doc_theme` value if it exists, which Retype will then revert to its default mode of tracking the system OS theme. 

Currently, Retype does not add the `doc_theme` local storage value until the theme button is clicked the first time.

**Comment by geoffreymcgill** [comment]
Okay, we might have fixed this issue of persisting the theme across sub-sites within the same domain or sub-domain. Persisting across different domains or even a domain and sub-domain of the same domain is not possible. 

- 🚫 `example.com` to `sample.com`
- 🚫 `example.com` to `docs.example.com`
- ✅ `docs.example.com` to `docs.example.com/project1`
- ✅ `docs.example.com/project1` to `docs.example.com/project2`

It was a relatively simple change but is going to require some testing to confirm. If testing confirms the fix is good, the change will be included in the next release, which is currently scheduled for v3.5.0.

**Comment by patricklafrance** [comment]
That would work for us as we expect to host all our sites with GitHub Pages and all repositories are under the same organization 🙏🏻 

It might be a good idea thought to keep an item in a backlog to investigate if the mecanism could be moved to cookies in order to allow cross domains and sub-domains.

**Comment by geoffreymcgill** [comment]
> if the mecanism could be moved to cookies in order to allow cross domains and sub-domains support.

It's not possible, at least with local storage, session storage, or cookies.

To make this work across domains or sub-domains would require a centralized service/server. That breaks the Retype decentralized model, so not something we could implement in the short-term. Long term, maybe.

**Comment by patricklafrance** [comment]
Sorry my bad, indeed cookies can't support cross domains but would allow sub-domains support.

**Comment by geoffreymcgill** [comment]
This enhancement has been included in the v3.5.0 release (now available). We have tested but we need some _real world_ projects to upgrade and confirm things are working as expected. 

When you get a chance, please upgrade to v3.5.0 and let us know what you think.

**Comment by patricklafrance** [comment]
Will do tonight!

Thank you for getting this out quickly, really appreciated 🙏

**Comment by patricklafrance** [comment]
Works pretty well with our hub :)

Thank you 🙏🏻

**Comment by geoffreymcgill** [comment]
A new `Light` | `Dark` | `System` switcher menu has been added to the latest `-preview` release and will be available in the upcoming `v3.11.0` release. Please see it working on the [retype.com](https://retype.com/) website.
