### ISSUE TITLE
The bottom padding/margin is missing when the ToC takes the full height of the page

### ISSUE THREAD

**Issue by patricklafrance** [retypeapp/retype#632]
The bottom padding/margin is missing when the ToC takes the full height of the page:

![image](https://github.com/retypeapp/retype/assets/794579/efee5243-ebb3-480e-9479-9f5790d73177)

The same issue exists on the Retype documentation website: https://retype.com/configuration/project/#url

Thank you,

Patrick

**Comment by geoffreymcgill** [comment]
I don't really see this as an issue. Do you feel there should be additional padding just at the bottom of the ToC column when the page content is scrolled to the bottom? or, more padding below each item no matter what position they are in the menu? And only more padding on the active items (blue items), or all menu items?

**Comment by patricklafrance** [comment]
Sorry for commenting again on this very **minor** issue 😆 

IMO, the bottom padding should be similar for both the sidebar menu and the ToC. Currently the sidebar bottom padding makes sense so the ToC bottom padding should probably use the same value as the sidebar bottom padding:

![image](https://github.com/retypeapp/retype/assets/794579/6bf3a89f-7d55-4c66-9f1d-a9c270267b66)

**Comment by geoffreymcgill** [comment]
Thanks for pointing this out. I will adjust and the fix will be included in the next release of Retype.

**Comment by geoffreymcgill** [comment]
The same padding has been added to the bottom of the ToC and will be included in the upcoming Retype v3.5.0 release.

**Comment by patricklafrance** [comment]
@geoffreymcgill I can confirm that the last item of the ToC is now spaced from the bottom.

However, it would be better to update the spacing of the container including the scrollbar rather than the last item of the ToC. Here's what I get with v3.5.0:

![image](https://github.com/retypeapp/retype/assets/794579/faad33a3-f2b0-4099-b641-4455c0fad34c)

If the container of the scrollbar would be spaced instead of the last item of the ToC, that would be similar to the left sidebar:

![image](https://github.com/retypeapp/retype/assets/794579/7f2bf425-d220-449b-aaec-fe21bca1b92d)

**Comment by geoffreymcgill** [comment]
The little bit of margin-bottom under the left tree nav has been removed. The change will be included in the next release of Retype.
