### ISSUE TITLE
Allow words to break for the ToC

### ISSUE THREAD

**Issue by patricklafrance** [retypeapp/retype#633]
Currently, if a word in the ToC is too long, an horizontal scroll is added and the user can scroll to see the whole word:

![image](https://github.com/retypeapp/retype/assets/794579/afa3f13b-aaaa-4333-b48b-ca9fbb73e19b)

While it's a good default fail-safe mecanism, I believe it would be better to allow long words to break and only rely on the horizontal scroll for major cases:

```css
.simplebar-content > li {
    word-break: break-word;
}
```

After the addition of the CSS:

![image](https://github.com/retypeapp/retype/assets/794579/abc2dfdb-6249-421f-b88c-11246fe01c1a)

Thank you,

Patrick

**Comment by geoffreymcgill** [comment]
Hi @patricklafrance. Can you provide more context or explanation, specifically regarding the following statement:

>  it would be better to allow long words to break and only rely on the horizontal scroll for major cases:

What do you mean by _major cases_?

If the heading is `defineDevRemoteModuleConfig`, do you feel Retype should split into two values, such as `defineDevRemoteModule` and `Config`?

**Comment by patricklafrance** [comment]
> What do you mean by major cases?

I mean if it would be a very large header like:

 "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam justo lacus, viverra vel egestas ac, facilisis quis tortor. Interdum et malesuada fames ac ante ipsum primis in faucibus."
 
 (I am not sure why someone would come up with such an header thought)
 
 It will probably be broken on multiple lines anyway. While thinking about this, I am not sure when it's a good thing to introduce the horizontal scrollbar. Do you have any usecases when it proved to be usefull?

> If the heading is defineDevRemoteModuleConfig, do you feel Retype should split into two values, such as defineDevRemoteModule and Config?

Yes, I think it should be broken into to values `defineDevRemoteModule` and `Config`. IMO, it is more convenient for the user than scrolling horizontally.

**Comment by patricklafrance** [comment]
If you are wondering what it would looks like, I added it as custom CSS to our public documentation websites:

- https://gsoft-inc.github.io/wl-squide/getting-started/
- https://gsoft-inc.github.io/wl-web-configs/

**Comment by geoffreymcgill** [comment]
`break-word` has been applied to the ToC items and Headings. The change will be included in the next release of Retype.

@patricklafrance Thanks for pointing out this issue.
