### ISSUE TITLE
Open external links in new tab

### ISSUE THREAD

**Issue by axonasif** [retypeapp/retype#64]
Hello, this is another feature request of mine.
I think it would be great if this is implemented in retype.
Or more like there should be a retype component which would allow us to do so.
Thanks!

**Comment by geoffreymcgill** [comment]
I've been thinking about adding a new `retype.json` global property that would allow customization of how external links are opened. 

Currently, all the `links` configs have a [`target`](https://retype.com/configuration/project/#target) option for managing where the topbar and footer links are opened. 

A new global property would be similar, but would manage all external links within the `.md` content only.

**Comment by DannyBen** [comment]
Just my two cents - having *all* external links open in a new tab is generally discouraged among UI experts. This is usually better left to the user to <kbd>Ctrl</kbd>`+ Click`.

Of course, there is no harm in having such a configuration.

**Comment by geoffreymcgill** [comment]
> Just my two cents - having _all_ external links open in a new tab is generally discouraged among UI experts. This is usually better left to the user to Ctrl`+ Click`.

Strongly agree. Any global project config that we add would default to _not_ opening external links in a new tab. Developers would need to explicitly enable that setting to open external links in a new tab.

**Comment by axonasif** [comment]
> > Just my two cents - having _all_ external links open in a new tab is generally discouraged among UI experts. This is usually better left to the user to Ctrl`+ Click`.
> 
> Strongly agree. Any global project config that we add would default to _not_ opening external links in a new tab. Developers would need to explicitly enable that setting to open external links in a new tab.

Actually I don't want all external links open in new tab, it would be better as a component to specifically make it happen for chosen links in a document. This is essential when you have a page with a set of instructions and you don't want the user to mistakenly leave the page in between.

**Comment by geoffreymcgill** [comment]
> it would be better as a component to specifically make it happen for chosen links in a document.

Yes, we can come up with a solution for this. I have some syntax ideas and will work out a plan to implement.

**Comment by fabriciomurta** [comment]
And, in the meanwhile, one can just `<a href=... target=_blank></a>` to force this to specific links. Just in case you really miss this feature and want it at once, no matter what.

**Comment by geoffreymcgill** [comment]
As of [Retype `v2.0.0`](https://github.com/retypeapp/retype/discussions/287#discussioncomment-2321442), you can now configure a `target="blank"` attribute on Markdown native hyperlink components using the generic attribute syntax. For example:

```md
[Click me](https://example.com){target="_blank"}
```

That generic attribute syntax does not currently work on Retype Components, such as Button and Badge, but we do hope to support in the future. For now, only Markdown native elements/components are supported. The following **will not work** (at least for now):

```
[!button Example](https://example.com/){target="_blank"}
```

but you can still configure Button and Badge `target`'s using the following syntax:

```
[!button text="Example" target="blank"](https://example.com/)
```

Hope this helps.
