### ISSUE TITLE
Question regarding Cloudflare

### ISSUE THREAD

**Issue by AMufInABox** [retypeapp/retype#649]
Hey! I was trying to use Cloudflare to put my docs using retype, But whenever I do so its not using my custom domain? It always goes to a page like for instance "https://retype.mr-poll-docs.pages.dev/* when I would want it to go to "https://test.mrpoll.dev/". Any way I could fix this?

**Comment by geoffreymcgill** [comment]
Hi @AMufInABox. My guess this is a Cloudflare Pages configuration issue and not something directly related to Retype. Best I can tell, you have the Retype project configured correctly and the project `url` setting is set to `https://mrpoll.dev/docs/`.

In the Settings for the Pages instance, you should see the option to setup a custom domain. Just double check that is all setup correctly from within Cloudflare.

<img width="552" alt="Screen Shot 2023-10-22 at 8 27 26 PM" src="https://github.com/retypeapp/retype/assets/62210/3ffbfc54-426e-4613-8da2-e8eff2e80b85">

Hope this helps.

**Comment by AMufInABox** [comment]
Yeah I had the custom domain set to 
![image](https://github.com/retypeapp/retype/assets/74741218/1396114c-b6a3-4d2f-90dd-c71e621087d5)
this ^

And on retype this was the url 
![image](https://github.com/retypeapp/retype/assets/74741218/d2461fca-9754-4cfb-a7eb-aa2a2838a846)

But even with that it just gives me this as well with a 404 so I'm unsure if I did anything wrong as the deployment works if I go to this url: https://16b0b891.mr-poll-docs.pages.dev/ but it doesnt work for my actual domain itself.
![image](https://github.com/retypeapp/retype/assets/74741218/675360c2-0762-4b26-a852-3e137ebcbe29)

**Comment by AMufInABox** [comment]
DNS Record: 
![image](https://github.com/retypeapp/retype/assets/74741218/5b34d81f-05fa-4e13-a088-2f393af72da6)

**Comment by AMufInABox** [comment]
Thanks!
