### ISSUE TITLE
Switch tabs without page reload and scroll

### ISSUE THREAD

**Issue by afaa97** [retypeapp/retype#651]
Hello, is there a way to switch tabs without the page reloading and scrolling? I'd like to use the anchor of Tab 2 as a link within Tab 1 and click on Tab 1 to transition to Tab 2 and so on.

An example:

![example](https://github.com/retypeapp/retype/assets/31856635/4985de72-4d83-4c62-a0c5-fc6e7a17f63b)

Edit: Okay scrolling would be ok if the current tab height is large.

**Comment by geoffreymcgill** [comment]
Unfortunately, Retype does not support this functionality currently, but I am going to investigate after the v3.6.0 release and try to get this working.

**Comment by geoffreymcgill** [comment]
This enhancement has been made and will be included in the next release of Retype. Now Retype supports linking directly into any Tab without a page reload. 

The following sample demonstrates the scenario.

```md
+++ Tab 1
This is Tab 1

[Tab 2](#tab-2)
+++ Tab 2
This is Tab 2

[Tab 3](#tab-3)
+++ Tab 3
This is Tab 3

[Tab 1](#tab-1)
+++
```

Hope this helps.
