### ISSUE TITLE
Retype fails to resolve anchor links to panels

### ISSUE THREAD

**Issue by Ravencentric** [retypeapp/retype#659]
```
WARNING: [guides\htpc.md:184] Page anchor "/guides/playback#explaining-judder" was not found.
```
Example: https://thewiki.moe/guides/playback/#explaining-judder

If the anchor goes to a panel like so:

```
==- Something
Lorem ipsum
===
```

Retype fails to resolve the anchor and throws a warning, although the anchor itself works when deployed

**Comment by geoffreymcgill** [comment]
Currently, Retype does not resolve Panel anchors. Linking to that anchor will work, but the link resolution logic within Retype just doesn't support that scenario yet. This is functionality we need to add. 

I'm going to close this issue in favour of keeping the conversation centralized in #389. 

## See also

- https://github.com/retypeapp/retype/issues/389#issuecomment-1217094451
