### ISSUE TITLE
Sitemap.xml and Robots.txt?

### ISSUE THREAD

**Issue by bountyx** [retypeapp/retype#66]
Would a generated site benefit from SEO by adding these two files?

**Comment by fabriciomurta** [comment]
Sitemap is being handled at #58, please follow it.

As for the robots file, at first, having it or not wouldn't change much how your site is indexed, unless you don't want some parts (or all) of it to be indexed. `site:retype.com config` seems well indexed, although there's no **robots.txt* file.

You can always create your custom robots file, and it will be published along with the documentation files.

If Retype had an admin panel or private area like WordPress, for instance, a **robots.txt** file would be interesting so search engines wouldn't try to index these parts of the site.

This may be interesting though to ensure pages not displayed in the navigation tree are not indexed; but on the other hand they should only be indexed if somewhere linked to, in which case, there's a fifty-fifty whether the author wants the page to be indexed or not.

**Comment by geoffreymcgill** [comment]
Hi @bountyx,

The `sitemap.xml` auto-generation functionality is being built next, although it might not make it into the upcoming `v1.8.0` release. We might have to wait for `v1.9.0`. 

Regarding `robots.txt`, as mentioned by Fabricio, you can manually create the `robots.txt` file and add to the root of your project. Retype will automatically move that file into the root of the built website. 

A basic `robots.txt` would be:

```txt
User-agent: *
Allow: /
```

In the past, I didn't feel Retype needed to auto-generate a `robots.txt` file, but with the upcoming `visibility: hidden` metadata config for pages, having Retype manage the `robots.txt` might be a good idea. We will investigate. It should be simple for us to include this functionality. Thanks for the request!

**Comment by geoffreymcgill** [comment]
Auto-generation of the `sitemap.xml` is complete, and it's working great. Super awesome. The functionality will be included in the upcoming `v1.8.0` release.

As well, included in `v1.8.0` release, we will auto-generate a basic `robots.txt` file. The auto-generated `robots.txt` file can be easily overwritten by including your own custom `robots.txt` file within the root of your project.

**Comment by motiejunas** [comment]
@geoffreymcgill How can I disable this feature?

**Comment by geoffreymcgill** [comment]
> How can I disable this feature?

I don't think Retype has a configuration to disable either sitemap.xml or robots.txt. 

You can create custom versions of each of those files which will override the auto-generated versions. 

Can I ask, why do you want to disable?

**Comment by AndreyChechel** [comment]
> You can create custom versions of each of those files which will override the auto-generated versions.

Correct, just add a custom `robots.txt`, `sitemap.xml` or `sitemap.xml.gz` to your `input` directory, and Retype will just copy them to the configured `output` directory.

**Comment by motiejunas** [comment]
> > You can create custom versions of each of those files which will override the auto-generated versions.
> 
> Correct, just add a custom `robots.txt`, `sitemap.xml` or `sitemap.xml.gz` to your `input` directory, and Retype will just copy them to the configured `output` directory.

Oh, this is great. Thank you.
