### ISSUE TITLE
How do I make a folder name fully lowercase?

### ISSUE THREAD

**Issue by Nzii3** [retypeapp/retype#664]
I am wanting to make the folder name below lowercase. I named it lowercase in my editor and also tried using an `index.yml` and did it lowercase there but it did not work and only shows capitalized.
![image](https://github.com/retypeapp/retype/assets/106406461/bb7cb2e2-4128-4c67-aa90-101d5eb24897)

**Comment by geoffreymcgill** [comment]
Hi @Nzii3,

You can either of the following techniques.

1. Add a title to the page as `# v1`

```md
# v1

test
```

2. Add the `label` page setting:

```md
---
label: v1
---
# My Page

test
```

If all you do is add a `v1.md` page to your project and do not add a page title or `label`, Retype will try to infer the page title from the filename, and by default, Retype will capitalize the first letter of that page title.

Hope this helps.

**Comment by Nzii3** [comment]
@geoffreymcgill The page is a folder, so I can't set a page title. I want the folder name to be not capitalized.

**Comment by geoffreymcgill** [comment]
The same `label` setting works for both pages and folders. You can set using either of the following techniques:

1. Add an `index.yml` file to the folder and use the `label` setting:

```yml
label: v1
```

2. Add a [default page](https://retype.com/configuration/page/#default-pages) to the folder, or add default page and set the `label`:

```md
# v1

Test
```

or 

```md
---
label: v1
---
# Sample

Test
```

Hope this helps.

**Comment by Nzii3** [comment]
@geoffreymcgill

**Comment by geoffreymcgill** [comment]
> How can I embed a website with `iframe` in a page? 

It would be best to start a new issue for this question.
