### ISSUE TITLE
Embedding a website in a page

### ISSUE THREAD

**Issue by Nzii3** [retypeapp/retype#665]
How can I embed a website with `iframe` in a page? Is it possible?

**Comment by geoffreymcgill** [comment]
You can use the `[!embed](url)` component, see https://retype.com/components/embed/.

```md
[!embed](https://retype.com)
```

Another option would be using raw HTML [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) tags. 

```html
<iframe width="300" height="200" src="https://retype.com"></iframe>
```

Hope this helps.
