### ISSUE TITLE
How to remove edit icon

### ISSUE THREAD

**Issue by Nzii3** [retypeapp/retype#667]
How do I remove this at the bottom of pages?

![image](https://github.com/retypeapp/retype/assets/106406461/1f5a7edf-11d7-4143-bda3-fba51d2e6d4c)

**Comment by geoffreymcgill** [comment]
Hello. In your `retype.yml` file, you might have an `edit` setting. Just remove the `edit` and any sub-settings, and the link should be removed. 

For example, in the retype.com [`retype.yml`](https://github.com/retypeapp/retype/blob/main/retype.yml) file, we would remove (or comment out) the following settings:

```yml
# edit:
  # repo: github.com/retypeapp/retype

```

Hope this helps.

**Comment by Nzii3** [comment]
Yup that works! Thanks.
