### ISSUE TITLE
Sidebar filter does not work for CamelCase titles

### ISSUE THREAD

**Issue by burukuru** [retypeapp/retype#696]
Given a page title of `GitOps`, searching in the sidebar filter for `git` will find a result but `gito` does not find anything.

<img width="344" alt="Screenshot 2024-05-10 at 12 01 22" src="https://github.com/retypeapp/retype/assets/3882632/2f49bd54-665e-47e9-ac64-cee190bc036a">
<img width="371" alt="Screenshot 2024-05-10 at 12 01 30" src="https://github.com/retypeapp/retype/assets/3882632/42a8e48a-7e09-468b-907d-fb797a13efd4">

Changing the title to `Gitops`, makes both search strings work fine.

We're using retype v3.5.0.

**Comment by geoffreymcgill** [comment]
Interesting and confirmed. I'm surprised this defect exists and that we haven't run into this issue in the past. Should be an easy fix and we will do our best to include the fix in the next release.

**Comment by geoffreymcgill** [comment]
This defect has been fixed and the fix will be included in the v3.6.0 release of Retype. I don't have a release date for v3.6.0 but we're working on it and our intention is to release as soon as possible.

No changes in your project will be required.

**Comment by burukuru** [comment]
Thanks for the speedy turnaround! Interestingly, it seems to work if there is more than one word in the title, e.g. `CamelCase Camel` will be shown when searching for `camelc`.
