### ISSUE TITLE
Double curly braces broken in codeblock

### ISSUE THREAD

**Issue by miku448** [retypeapp/retype#705]
I'm trying to create a codeblock that explains how to use templates `{{user}}`

For example, I want to display this codeblock using retype:
```
Hello {{user}}!
```

but the substring `{{user}}` gets deleted inside the codeblock when rendered. I think because it thinks it's a variable.

**Comment by geoffreymcgill** [comment]
The post should help, see https://github.com/retypeapp/retype/issues/426#issuecomment-1273342318

Any other those four options should work-around the issue you are having. 

Hope this helps.
