### ISSUE TITLE
Incompatible Retype licence and CLI

### ISSUE THREAD

**Issue by markbattistella** [retypeapp/retype#710]
I've tried installing the previous versions of Retype which I have 3 licences for - v3.5 - but I cannot install them to the wallet on my machine:

```text
ERROR: Failed to save the wallet. This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release.
```

Upgrading to v3.6 of Retype the error changes:

```text
ERROR: Retype license unlocks a different version.
         - Status:                       Incompatible Retype version
         - Expires:                      Never
         - Free upgrades until:          2023-11-09 08:35
         - Max pages:                    1000
         - Hosts:                        abc.efg.com
```

```shell
user@machine ~ % retype wallet --list
Your wallet is empty.
```

I understand that my licence has expired, but I cannot add it to the wallet to allow the 1000 page or use Retype at the version I upgraded until.

At this point I cannot build my site because it reports this error:

```sh
user@machine ~ % npm list -g                   
/usr/local/lib
└── retypeapp@3.5.0
```

```sh
user@machine ~ % retype build                  
  INPUT: /my-site
 OUTPUT: /my-site/docs
ERROR: This release of Retype has expired. Please update to the latest release. A Retype license is required to continue using this release.
```

Upgrading to v3.6:

```sh
user@machine ~ % npm list -g                   
/usr/local/lib
└── retypeapp@3.6.0
```

```sh
user@machine ~ % retype build                  
  INPUT: /my-site
 OUTPUT: /my-site/docs
WARNING: [retype.yml]: The "Powered by Retype" logo removal requires a Retype Pro license.
WARNING: [retype.yml]: The "outbound" feature requires a Retype Pro license.
         Please use --verbose for more details

Retype finished in 1.5 seconds!
  16 pages built
   0 errors
   2 warnings
```

I was under the impression that I could install the last updated version when I was within the free upgrades (which was v3.5) and remain on that version until I needed to upgrade:

> You decide NOT to renew your Retype key 😢. No worries. Your project will continue to build forever, except you cannot upgrade the project to the next Retype release. You would stay on the current release.
>
> You would be able to upgrade Retype up until v5.0.
>
> Installing Retype v5.1 would be possible, but your project would fail to build. You would have to downgrade back to v5.0 or renew your Retype Pro license.
> 
> You would still be able to build up to 1000 pages and remove the Powered by Retype branding, but only if using the release at the time your key expired. Again, you just would not be able to upgrade to any future releases.
>
> From: https://retype.com/pro/#scenario-2-no-renew

**Comment by geoffreymcgill** [comment]
There is a defect in the license key check. Please email (hello@retype.com) me and I will create some new licenses for you that will validate on v3.6.0.

**Comment by geoffreymcgill** [comment]
@markbattistella I sent you an email with new license keys.

**Comment by markbattistella** [comment]
Thank you @geoffreymcgill! That email seemed to solve it
