### ISSUE TITLE
Format on blockquote: Excessive bottom spacing

### ISSUE THREAD

**Issue by devon** [retypeapp/retype#74]
```
I don't know. Do you?

> I don't know either.
```

<img width="705" alt="Screen Shot 2021-07-14 at 10 45 25 AM" src="https://user-images.githubusercontent.com/8176/125552881-c8a9b8b5-f50c-405c-9364-e5d9c6ffa66b.png">

**Comment by geoffreymcgill** [comment]
Thanks for the report. Looks like this is extra margin is only happening in `light` mode. When the page is in `dark` mode, the margin is good. 

<img width="294" alt="Screen Shot 2021-07-13 at 10 50 36 PM" src="https://user-images.githubusercontent.com/62210/125553378-27a63482-cb26-4103-88d2-5422e998083a.png">
<img width="276" alt="Screen Shot 2021-07-13 at 10 50 26 PM" src="https://user-images.githubusercontent.com/62210/125553383-ce554431-4889-48e5-9aa0-c27a3aeb1d16.png">

Should be an easy fix. I will try and get this into the upcoming `v1.8.0` release.

**Comment by geoffreymcgill** [comment]
This issue has been fixed and the fix will be included in the Retype `v1.8.0` release. While debugging this issue, I also found another `blockquote > p` scenario that was not rendering correctly, and that scenario is now fixed too.

Thanks again for letting us know!
