### ISSUE TITLE
Listen on 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by DannyBen** [retypeapp/retype#86]
Hello,

First of all, I am very excited about this tool. It looks very polished and lightweight, and very easy to use.

I noticed that the `watch` and `run` command only allow setting the `--port` but not the bind address, and it listens on `localhost`. In some scenarios - like mine, when using Vagrant - there is a need to listen on `0.0.0.0` instead.

Is there a plan on adding such option?

**Comment by geoffreymcgill** [comment]
Great idea. Maybe we can call the command `--hostname`. 

The `port` config in `retype.json` should likely be moved into a new `watch` config object. For instance:

```json
{
    "watch": {
        "port": 5005,
        "hostname": "0.0.0.0"
    }
}
```

This would also allow configuring the `hostname` to serve from a machine name or local domain. I think. 

One BIG warning, `retype watch` should not be used in production. It's a development server only.

**Comment by fabriciomurta** [comment]
we could bundle in a `bind` so port would be optional. Maybe address would fit better as it might be bindable by IP, host, and maybe even interface (some applications allow to bind a service to a given physical network card/port, but I suppose that'd be less "cross-platform friendly").

So both would be valid:
```
{
   "watch": {
       "port": 5005,
       "address": "0.0.0.0"
   }
}
```

```
{
   "watch": {
       "address": "0.0.0.0:5005"
   }
}
```

So, then, commandline could be
```
--watch-address 0.0.0.0 --watch-port 5005
--watch-address 0.0.0.0:5005
```

**Comment by DannyBen** [comment]
Wow - you guys are active! I love it, I can't go to sleep since I found it - I have tried all alternatives, and retype is by far the most handsome doc builder - the attention to details in this project is very obvious.

Yes - I know watch is only for dev. I intend to just build do `docs` and push to GitHub pages (no need for GitHub actions even) - I am doing it in some other projects (currently using mdbook).

As for the issue at hand: For now - I am managing without this listen address, I strapped on a `Procfile` that watches, builds, and I just serve the static output.

I don't have an opinion about the config, since I have not used it yet - but a few thoughts on the command line:

1. In the big majority of cases I have seen, it is simply called `--host <address>`
2. In a small number of cases, it is `--bind <address>`.
3. I suggest sticking to one of these,
4. In about 70% of the time, the default is actually `0.0.0.0` and not `localhost`. I guess many authors encountered "I can't connect" issues, that they defaulted to `0.0.0.0` to eliminate all issues.
5. If I understand correctly and this function has an equivalent in the config, it should be called the same if possible.

Anyways, thanks again.

**Comment by geoffreymcgill** [comment]
> In the big majority of cases I have seen, it is simply called --host <address>

ya, `--host` is much better. I like it. 

> In about 70% of the time, the default is actually 0.0.0.0 and not localhost. I guess many authors encountered "I can't connect" issues, that they defaulted to 0.0.0.0 to eliminate all issues.

Interesting. We will review our decision to use `localhost`.

**Comment by geoffreymcgill** [comment]
@DannyBen Can I get your feedback on some config naming? 

We are adding the `--host <address>` command to the Retype CLI in `v1.8.0`. We will also be adding the option to configure within `retype.json`.

This is our proposal for the `retype.json` config names:

```json
{
  "serve": {
    "port": 5005,
    "host": "127.0.0.1"
  }
}
```

Thoughts on using the name `serve`? Anything better?

Here's the current list of names we have brainstormed:

```
dev
serve
bind
watch
run
local 
server
debug
hosting
```

The CLI commands would remain `--port <number>` and `--host <address>`.

Another option is to just support the config names within the root `retype.json` class. For instance:

```json
{
  "port": 5005,
  "host": "127.0.0.1"
}
```

Do you have a preferred approach?

**Comment by DannyBen** [comment]
Thank you for asking, makes me feel all warm inside :)
I love retype so much, I almost forgot to eat all day...

My loosely-held, strong opinion is this:

- `host` is perfect - both for config and `--host` for CLI
- `server` is a little better in my mind than `serve`. I am configuring the server.
- I prefer this config under `server` and not root - keep root clean for absolute basic things (as it is now).

So, my humble vote:

```json
{
  "server": {
    "port": 5005,
    "host": "127.0.0.1"
  }
}
```

On a side note, I wish `retype.json` was in fact `retype.yml`... it is so much more user friendly and pleasant, and less prone to errors. Any chance of that happening?

```yaml
input: src
output: docs
server:
  host: 0.0.0.0
  port: 3000
branding:
  logo: assets/logo.svg
  logoDark: assets/logo-dark.svg
  label: v0.6.1
```

**Comment by geoffreymcgill** [comment]
Thanks for the awesome feedback. We're going with:

```json
{
  "server": {
    "port": 5005,
    "host": "127.0.0.1"
  }
}
```
and will include in `v1.8.0`.

**Comment by geoffreymcgill** [comment]
Regarding...

> On a side note, I wish retype.json was in fact retype.yml... it is so much more user friendly and pleasant, and less prone to errors. Any chance of that happening?

![thats-a-great-idea](https://user-images.githubusercontent.com/62210/126715847-aa945899-9fdb-48b2-b3da-2b1ecba8f5d2.gif)

**Comment by DannyBen** [comment]
> Regarding...

Heh! I am so happy to hear that. YAML is for people, JSON is for machines.

**Comment by geoffreymcgill** [comment]
> Heh! I am so happy to hear that. YAML is for people, JSON is for machines.

Yes, agreed. Very valid point.

We should have just supported `retype.yml` from the beginning, but the idea only got cursory consideration and was dropped. 

Retype will support both `retype.yml` and `retype.json`. It's easy for us to support both, but `retype.yml` will be the preferred (and default) project configuration file format.

`retype.yml` will be for people. 

`retype.json` will be for machines.

**Comment by geoffreymcgill** [comment]
The `--host <address>` command has been added to the Retype CLI.

All the following samples are possible.

### Samples

```
retype watch --host localhost
retype watch --host 0.0.0.0
retype watch --host 127.0.0.1
retype watch --host 127.0.0.1 --port 5005 # pass host and port separately
retype watch --port 5005 # port only
retype watch --host 127.0.0.1:5005 # include port with host
retype watch --host <your-machine-name>
retype watch --host [::]:5000
retype watch --host [::1]:5000
```

IPv6 addresses are also supported.

If an explicit `--port` value is supplied, it will override any port value that might have been included in the `--host`.

As well, you can configure within your projects `retype.json` file.

```json
{
  "server": {
    "host": "127.0.0.1",
    "port": 5005
  }
}
```

Both `server.host` and `server.port` are optional. By default, Retype will still serve from `localhost:5000`.

The `--host` and `--port` commands take precedence over the `server.host` and `server.port` configs in the `retype.json`.

Retype will also watch for any `server.host` or `server.port` changes in the `retype.json`. If changed, the server will be restarted and a page for the new URL will be opened in a browser.

These new features will be included in the upcoming Retype `v1.8.0` release.

Hope this helps.

**Comment by geoffreymcgill** [comment]
> On a side note, I wish retype.json was in fact retype.yml... it is so much more user friendly and pleasant, and less prone to errors. Any chance of that happening?

Status update. We will be including `retype.yml` in `v1.8.0`. The bulk of the functionality was built today, but there's still a lot of testing to complete and few edge cases to deal with.

We are also making `retype.yml` the default project config file type, so when `retype init` is run (or `retype watch`) on a fresh project, a `retype.yml` file will be created, instead of `retype.json`. 

The `retype.json` will also continue to be fully supported, so introducing `retype.yml` to Retype does not create a breaking change in the next release. It's just a new added feature and should be a seamless _drop in_ upgrade from `v1.7.0` to `v1.8.0`. 

Both `retype.yml` and `retype.yaml` file types are supported.

I would anticipate the `retype.yml` functionality being complete early next week, with the public `v1.8.0` release to follow almost immediately thereafter.

**Comment by DannyBen** [comment]
Confirmed in version `1.7.1-202107290616`

- `retype.yml` works, and my config files are now much more readable!
- `retype run` and `retype watch` both obey the `server.host` and `server.port` 
-
