### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by noraj** [retypeapp/retype#9]
Like almost all documentation staticgen it lacks of tag support.

I explained the idea extensively here: https://github.com/intuit/Ignite/issues/126

**Comment by geoffreymcgill** [comment]
We were already in the process of building `tags` support into the new Blog pages. It shouldn't be a problem for us to add to regular pages too. At this point, I can't say when `tags` will be supported, but I'll try and prioritize adding the feature.

Thanks for the suggestion. 👍

**Comment by noraj** [comment]
Awesome news, I'm eager to see that in action.

**Comment by geoffreymcgill** [comment]
@noraj Tags are being built right now. We have the functionality working and will be including in the `v1.6` release. Still lots to do though. At this point, we don't have a release date set for `v1.6`, although 2-3 weeks would be a reasonable timeline.

**Comment by noraj** [comment]
Awesome news.
I won't miss that if you push a git tag or GH release.

![image](https://user-images.githubusercontent.com/16578570/119100800-9d8a4c80-ba18-11eb-854a-9216a30dd1bf.png)

**Comment by geoffreymcgill** [comment]
The new `tags` functionality has been included in the Retype `v1.6.0` release.

A list of `tags` can be added to the metadata at the top of each `.md` page you would like to _tag_. 

Here is a `sample.md` page demonstrating how to add the `tags` metadata:

```
---
tags: [guide]
---
# Page title

Some content here.
```

Multiple tags can be added to the `tags` array. Here is a `sample.md` page demonstrating multiple `tags`:

```
---
tags: [guide, config options, installation]
---
# Page title

Some content here.
```

A summary page for each `tag` ([example](https://retype.com/tags/guide/)) is automatically generated by Retype, as well as a  `/tags/` index page ([example](https://retype.com/tags/)) listing all Tags within the project.

More [`tags`](https://retype.com/configuration/page/#tags) documentation is being written right now and will be available online soon, but it's a simple (yet POWERFUL 💪) feature that should _just work_ once you add the `tags` config to your page(s).

We noticed a few other static site generators take a half-baked approach to tag linking within the project, where they just link the Tag to some search results. Retype creates proper Tag summary and index pages that are nicely formatted, and like all pages, they are generated at ⚡lightning⚡ speed by Retype.

Thanks again @noraj for the feature request! Please let us know if you have any further suggestions or feedback and we will do our best to assist.

Hope this helps.

**Comment by noraj** [comment]
@geoffreymcgill Nice feature, well implemented, good release note and thx to keep me informed. Also congratz Retype is nearly the only documentation staticgen to support tags for (documentation) pages and not only for blog posts.
I have to try this by myself now.

**Comment by geoffreymcgill** [comment]
@noraj I forgot to mention, but the following `tags` syntax is also supported:

```
---
tags:
    - dev
    - python
---
```

Individual tag pages will be automatically created at https://example.org/tags/dev and https://example.org/tags/python, plus an additional `/tags` summary index page which lists all tags used within the project.

Hope this helps.
